(function(z){
var tG=function(a,b,c){b=(b||a.xd)===z.ks.Hd;return c?(a=a.d.u.w().get(z.U.Sq),b?-1:-a):a.Bo+(b?-1:1)};var uG=function(a){z.as.call(this,a);this.Bo=0;this.xd=z.ks.Hd};var vG=function(a,b,c,d,f){var g=b.get(b.g.gd);if(g===z.Q.id)throw"liked_own_comment";var h={Wa:b.id,xa:a.d.u.w().id},k=z.wr.D(),n=c?"like":"unlike";c&&a.d.L("quill_like_recv",{tn:b.id,pK:g});k.Hp(h,(0,z.Pk)(z.Q),n,d,f)};
var wG=function(a,b){var c=a.Fb.ss(b),d=new z.Xr;d.yx=function(a){return(0,z.je)(a,function(a){return a.content.ancestorId==b.id})};a.Fb.Ni(c,d);return d};var xG=function(a,b){a.YX=b};var yG=function(a){return'\x3ca href\x3d"'+(0,z.ym)(a.Ka)+'" title\x3d"'+(0,z.S)(a.$)+'" data-id\x3d"'+a.id+'" class\x3d"fyre-follower fyre-follower-'+a.uU+'"\x3e\x3cimg src\x3d"'+(0,z.ym)(a.Fc)+'" alt\x3d"'+(0,z.S)(a.$)+'" onerror\x3d"javascript:this.src\x3d\''+(0,z.S)(a.Sb)+"';\" /\x3e\x3c/a\x3e"};
var zG=function(a){return(0,z.Cp)(a)+'\x3cdiv class\x3d"fyre-archive-stream-sort fyre-stream-sort"\x3e\x3ch3\x3e\x3cstrong\x3e\x3c/strong\x3e'+(0,z.S)(a.l.UO)+'\x3c/h3\x3e\x3cdiv class\x3d"fyre-stream-sort-options"\x3e\x3ca class\x3d"fyre-stream-sort-newest fyre-stream-sort-selected"\x3e'+(0,z.S)(a.l.mz)+'\x3c/a\x3e\x3cspan class\x3d"fyre-stream-sort-bar"\x3e'+(0,z.S)(a.l.mq)+'\x3c/span\x3e\x3ca class\x3d"fyre-stream-sort-oldest"\x3e'+(0,z.S)(a.l.oz)+"\x3c/a\x3e\x3c/div\x3e\x3c/div\x3e"};
var AG=function(a){return'\x3cdiv class\x3d"fyre '+(a.se?"fyre-liveblog ":"")+(a.Dh?"fyre-livechat ":"")+(a.HU?"fyre-bootstrap":"")+'"\x3e\x3cdiv class\x3d"fyre-widget '+(a.ab?"fyre-avatar-disabled":"")+'"\x3e'+(a.hx?(0,z.vp)(a):"")+'\x3cdiv class\x3d"fyre-featured-content-wrapper" style\x3d"display: none"\x3e\x3c/div\x3e\x3cdiv class\x3d"fyre-stream-stats"\x3e\x3cdiv class\x3d"fyre-comment-count"\x3e\x3c/div\x3e\x3cdiv class\x3d"fyre-help"\x3e\x3c/div\x3e\x3c/div\x3e\x3cdiv class\x3d"fyre-auth"\x3e\x3cdiv class\x3d"fyre-login-bar"\x3e\x3c/div\x3e\x3cdiv class\x3d"fyre-live-container"\x3e\x3cdiv class\x3d"fyre-livecount"\x3e\x3c/div\x3e'+
(a.ab?"":'\x3cdiv class\x3d"fyre-listener-avatars"\x3e\x3c/div\x3e')+'\x3c/div\x3e\x3c/div\x3e\x3cdiv class\x3d"fyre-editor"\x3e\x3c/div\x3e\x3cdiv class\x3d"fyre-input-box-collapsed"\x3e\x3c/div\x3e\x3cdiv class\x3d"fyre-stream-header"\x3e\x3c/div\x3e\x3cdiv class\x3d"fyre-comment-stream"\x3e\x3c/div\x3e\x3cdiv class\x3d"fyre-top-content-stream"\x3e\x3c/div\x3e\x3cdiv class\x3d"fyre-thread-breakout-stream"\x3e\x3c/div\x3e'+(a.xp?'\x3cdiv class\x3d"fyre-archive-stream-header"\x3e\x3c/div\x3e\x3cdiv class\x3d"fyre-archive-stream"\x3e\x3c/div\x3e':
"")+'\x3cdiv class\x3d"fyre-stream-menu-container"\x3e\x3c/div\x3e\x3c/div\x3e\x3c/div\x3e'};var BG=function(a){return'\x3cdiv class\x3d"tooltip"\x3e'+(0,z.S)(a.message)+'\x3c/div\x3e\x3cdiv class\x3d"arrow-down"\x3e\x3c/div\x3e'};var CG=function(){};var DG=function(a,b){z.Zi.call(this,b,a)};var EG=function(a,b){z.uv.call(this,a,b)};
var FG=function(a,b){var c=a.d.Fb;c.bi[4]&&((0,z.bv)(c,4,(0,z.r)(function(a){b.f(a,"threadBreakout",this.Ns)},a)),(0,z.dv)(c,4,(0,z.r)(function(a){b.$a(a,"threadBreakout",this.Ns)})))};var GG=function(a,b){var c=[a.qn,a.DA];a.Sg&&c.push(a.Sg);a.Au&&c.push(a.Au);a.EA&&c.push(a.EA);(0,z.x)(c,function(a){(0,z.Xe)(a,"fyre-stream-sort-selected")});(0,z.N)(b,"fyre-stream-sort-selected")};var HG=function(a,b){z.uv.call(this,a,b)};
var IG=function(a,b){z.hu.call(this,a,b);this.Qd=!1;this.Ra=new z.pu;this.Ra.pc(this);this.Jv="archiveShowMore"};var JG=function(a,b){z.sv.call(this,a,b)};var KG=function(a,b,c){z.xq.call(this,a,b,c);this.XA=b||"";this.Ce(BG(this.r()))};var LG=function(a,b,c){z.rq.call(this,a,b||3,c)};var MG=function(a,b){z.T.call(this,b);this.k=a};var NG=function(a,b){z.T.call(this,b);this.Wc=a};var OG=function(a,b){NG.call(this,a,b)};var PG=function(a,b,c,d,f){z.tv.call(this,a,b,c,d,f)};
var QG=function(a,b){z.Cv.call(this,a,b);var c=a.u.Nc(),d=a.u.w();this.Gg=new PG(a,c,a.Jp.Vb,d.Dh()||z.Yb);this.K(this.Gg);a.Z.ab||(this.Po=new OG(c),this.K(this.Po));this.Ss=new z.rv;this.K(this.Ss)};var RG=function(a){z.Zm.call(this,a)};var SG=function(a){z.gv.call(this,a);this.bo=1};var TG=function(a){z.yp.call(this,a);(0,z.Cr)(a.u);this.Cc=new QG(a);this.is.start();this.Fm(this.Cc);(0,z.Bp)(this)};var UG=function(a,b){this.vE=DG;this.XK=TG;z.W.pq(b.strings||{});z.Bk.call(this,a,b)};
var VG=function(a){a.jl&&(a.jl.q(),delete a.jl)};(0,z.u)(uG,z.as);uG.prototype.nm=(0,z.da)(2);uG.prototype.iH=(0,z.da)(35);uG.prototype.jH=(0,z.da)(13);z.wr.prototype.Hp=(0,z.jd)(44,function(a,b,c,d,f){var g={message_id:a.Wa,collection_id:a.xa};this.uc(b,"message/"+a.Wa+"/"+c+"/",d,f).send(g)});z.Nr.prototype.Hp=(0,z.jd)(43,function(a,b,c){vG(this,a,!0,b,c)});uG.prototype.iH=(0,z.jd)(35,function(a){this.Pa||(this.Xp[a]=!1,(0,z.bs)(this,a,function(a){a.L(a.M.Zn)}))});
z.tr.prototype.Oi=(0,z.jd)(27,function(a,b,c){a=(0,z.ua)("%s%scollection/%s/hot/",z.w.P.Jd,z.w.of,a.xa);(new z.Kl({url:a,ua:b,qa:c})).send()});z.us.prototype.Oi=(0,z.jd)(26,function(a){var b={xa:this.d.u.w().id},c=z.tr.D().Oi;(0,z.vs)(this,c,b,a);return a});z.RA.prototype.Oi=(0,z.jd)(25,function(){(0,z.zs)(this);this.wj=new z.us(this.C,void 0);var a=new z.Xr;this.wj.Oi(a);return a});z.T.prototype.nI=(0,z.jd)(21,(0,z.e)("ca"));z.Wi.prototype.xp=(0,z.jd)(16,function(){return this.get(this.g.Rq)});
z.Nr.prototype.HK=(0,z.jd)(14,function(a,b,c){vG(this,a,!1,b,c)});uG.prototype.jH=(0,z.jd)(13,function(a,b){if(!this.Pa){var c=this.d.u.w(),d=(0,z.br)(a,b);c.set(z.U.Sq,d.CV);(0,z.A)(d.eb,(0,z.r)(this.d.S.L,this.d.S,"bootstrap_author_received"));(0,z.A)(d.content,function(a){(0,z.B)(d.content,(0,z.cs)(this,a))},this);(0,z.B)(this.ad,(0,z.ie)(d.content,(0,z.cb)(a)));this.xf(a,d.content);(0,z.bs)(this,a,function(b){b.L(b.M.Gl,{ff:a});b.set(b.g.jg,!0)})}});
z.tr.prototype.Li=(0,z.jd)(7,function(a,b,c){a=(0,z.ua)("%s%scollection/%s/top/%s/",z.w.P.Jd,z.w.of,a.xa,a.NO);(new z.Kl({url:a,ua:b,qa:c})).send({format:"stream"})});z.us.prototype.Li=(0,z.jd)(6,function(a,b){var c={xa:this.d.u.w().id,NO:a},d=z.tr.D().Li;(0,z.vs)(this,d,c,b);return b});z.RA.prototype.Li=(0,z.jd)(5,function(a){(0,z.zs)(this);this.wj=new z.us(this.C,void 0);var b=new z.Xr;this.wj.Li(a,b);return b});
uG.prototype.nm=(0,z.jd)(2,function(a,b){this.Bo=a;this.xd=b||this.xd;var c=this.Vd[a]=new z.Xr;z.tr.D();var d=this.d.u.w(),f=(0,z.r)(this.jH,this,a),g=(0,z.r)(this.iH,this,a),h=this.d.Z.Ul,d=d.get(z.U.Tc),h=z.w.uw(d,h)+String(a)+".json";(0,z.ur)(0,h,f,g);return c});z.RA.prototype.nm=(0,z.jd)(1,function(a,b){this.Sl||(this.Sl=new uG(this.C));var c=this.Sl,d=tG(c,a,b);return c.nm(d,a)});(0,z.u)(CG,z.Hk);(0,z.Ie)(CG);
CG.prototype.bI=function(a){var b={};b.Ul=a[z.lB.wB];var c=a[z.lB.yB];c&&(b.YO=c);if(c=a[z.lB.zB]||z.Yb&&(0,z.ga)(z.fyre.sp))b.DE=c;b.Fr=a[z.lB.CB]?!0:!1;c=a[z.lB.Ml];b.dh=c?c:!1;if(c=a[z.lB.GB])b.la=c;if(c=a[z.lB.fg])b.Xj=c;if(c=a[z.lB.KB])b.Jw=c;b.ke=(0,z.Ik)(this,a[z.lB.QB]);if(c=a[z.lB.YB])b.Gi=c;if(c=a[z.lB.iD])b.Rf=c;if(c=a[z.lB.yD])b.sA=c;c=a[z.lB.BD];null!=c&&(b.zA=c);if(c=a[z.lB.RB]||!1)b.ab=c;b.readOnly=a[z.lB.READ_ONLY]||!1;if(c=a[z.lB.YD])b.SK=c;if(c=a[z.lB.In])b.Ei=c;b.mf=a[z.lB.Tc];
b.mx=(0,z.Jk)(a[z.lB.tB]);c=a[z.lB.fL];b.mw=(0,z.He)(c)?c:!0;a=a[z.lB.kM];b.Cx=(0,z.He)(a)?a:!0;return b};(0,z.u)(DG,z.Zi);DG.prototype.oA=function(a){this.bl=new z.nr(this);this.bw=new z.Xq(this,a);this.zb=new z.Xl(this);this.ya=new z.Nr(this,a);this.Jp=new z.Tr(this);this.u=new z.zr(this,a);this.lb=new z.RA(this,a);new z.kl;this.vq=new z.Ls(this,a);this.Fb=new z.Su(this)};(0,z.u)(EG,z.uv);z.m=EG.prototype;z.m.r=function(){var a={},b=this.d.u,c=b.w();a.dz=b.w().se();a.zV=!z.Q.get(z.Q.g.rc);a.yk=b.yk(z.Q.id);a.YP=2===c.get(z.U.Kl);a.XP=3===c.get(z.U.Kl);a.l={XU:z.W.get(z.W.e.mv),$U:z.W.get(z.W.e.nv),sU:z.W.get(z.W.e.GC),mz:z.W.get(z.W.e.tv),oz:z.W.get(z.W.e.wv),mq:z.W.get(z.W.e.ID),Dq:z.W.get(z.W.e.or),jY:z.W.get(z.W.e.VD)};return a};
z.m.F=function(a){EG.b.F.call(this,a);a=this.c;var b;b=this.r();b=(0,z.Cp)(b)+(b.dz?'\x3ca class\x3d"fyre-follow-conversation"\x3e'+(b.zV?b.yk?(0,z.S)(b.l.$U):(0,z.S)(b.l.XU):"")+"\x3c/a\x3e":"")+'\x3cdiv class\x3d"fyre-stream-sort"\x3e\x3cdiv class\x3d"fyre-stream-sort-options"\x3e\x3ca class\x3d"fyre-stream-sort-newest fyre-stream-sort-selected"\x3e'+(0,z.S)(b.l.mz)+'\x3c/a\x3e\x3cspan class\x3d"fyre-stream-sort-bar"\x3e'+(0,z.S)(b.l.mq)+'\x3c/span\x3e\x3ca class\x3d"fyre-stream-sort-oldest"\x3e'+
(0,z.S)(b.l.oz)+"\x3c/a\x3e"+(b.YP?'\x3cspan class\x3d"fyre-stream-sort-bar"\x3e'+(0,z.S)(b.l.mq)+'\x3c/span\x3e\x3ca class\x3d"fyre-stream-sort-top-comments"\x3e'+(0,z.S)(b.l.jY)+"\x3c/a\x3e":"")+(b.XP?'\x3cspan class\x3d"fyre-stream-sort-bar"\x3e'+(0,z.S)(b.l.mq)+'\x3c/span\x3e\x3ca class\x3d"fyre-stream-sort-hot-threads"\x3e'+(0,z.S)(b.l.sU)+"\x3c/a\x3e":"")+'\x3c/div\x3e\x3ca class\x3d"fyre-stream-sort-back"\x3e\x3c/a\x3e\x3c/div\x3e';a.innerHTML=b;this.mm=this.o("fyre-follow-conversation");this.Au=
this.o("fyre-stream-sort-hot-threads")||null;this.EA=this.o("fyre-stream-sort-top-comments")||null;this.Sg=this.o("fyre-stream-sort-back");this.qn=this.o("fyre-stream-sort-newest");this.DA=this.o("fyre-stream-sort-oldest");this.jK=this.o("fyre-stream-sort-options");this.dc=this.o("fyre-content-loading");this.nd()};z.m.m=function(){EG.b.m.call(this);var a=this.p();z.Q.on(z.Q.M.Ie,this.yg,this);a.f(this.c,"click",this.mb);(0,z.x)([3,4,5],function(b){(0,z.vv)(this,a,b)},this);FG(this,a)};
z.m.mb=function(a){a.preventDefault();a=a.target;if(!(0,z.af)(a,"fyre-stream-sort-selected")&&"A"===a.tagName&&a!==this.Sg)if(a===this.mm)this.hH();else switch(GG(this,a),this.Xf(),a){case this.Au:this.aG();break;case this.EA:this.dispatchEvent({type:"sortTopComments",wb:(0,z.r)(this.nd,this)});break;case this.qn:this.Io(z.ks.Hd);break;case this.DA:this.Io(z.ks.hr)}};z.m.oj=function(a,b){a&&this.qA(b);(0,z.Zh)(this.jK,"display",a?"none":"block");(0,z.Zh)(this.Sg,"display",a?"block":"none")};
z.m.qA=function(a){var b=this.qn,c=this.Io,d=z.W.get(z.W.e.Vu);4===a&&(b=this.Au,c=this.aG,d=z.W.get(z.W.e.lL));this.Sg.innerHTML=d;this.p().zk(this.Sg,"click",(0,z.r)(function(a){a.stopPropagation();this.oj(!1);GG(this,b);c.apply(this)},this))};z.m.mp=function(a){a.stopPropagation();this.oj(!1);GG(this,this.qn);this.Io()};z.m.Ns=function(a){var b=a.wb;(0,z.B)(a,{wb:(0,z.r)(function(){b();this.oj(!0,4)},this)})};
z.m.Io=function(a){this.dispatchEvent({type:"sortOrderChanged",direction:a||z.ks.Hd,wb:(0,z.r)(this.nd,this)})};z.m.aG=function(){this.dispatchEvent({type:"sortHotThreads",wb:(0,z.r)(this.nd,this)})};z.m.hH=function(){var a=this.d.u;a.w();var b=z.Q.g;z.Q.id?(b=a.yk(z.Q.get(b.fa)),a.qs(!b),a=b?z.W.get(z.W.e.mv):z.W.get(z.W.e.nv),this.mm.innerHTML=a):(0,z.Zl)(this.d.zb,(0,z.r)(this.hH,this))};
z.m.yg=function(){var a=this.d.u,b=a.w(),c=z.Q.g,b=!b.se()||z.Q.get(c.rc);this.mm&&(b?(0,z.P)(this.mm,!1):(a=a.yk(z.Q.id)?z.W.get(z.W.e.nv):z.W.get(z.W.e.mv),this.mm.innerHTML=a,(0,z.P)(this.mm,!0)))};z.m.j=function(){EG.b.j.call(this);z.Q.off(null,null,this)};(0,z.u)(HG,EG);HG.prototype.F=function(a){this.c=a;(0,z.rm)(a,zG,this.r());this.qn=this.o("fyre-stream-sort-newest");this.DA=this.o("fyre-stream-sort-oldest");this.jK=this.o("fyre-stream-sort-options");this.dc=this.o("fyre-content-loading");this.nd()};HG.prototype.Io=function(a){this.dispatchEvent({type:"archiveSortOrderChanged",rj:this.YX.rj,direction:a,wb:(0,z.r)(this.nd,this)})};
HG.prototype.r=function(){return{l:{UO:z.W.get(z.W.e.gL),mz:z.W.get(z.W.e.tv),oz:z.W.get(z.W.e.wv),mq:z.W.get(z.W.e.ID),Dq:z.W.get(z.W.e.or)}}};(0,z.u)(IG,z.hu);z.m=IG.prototype;z.m.qo=function(a){this.clear();(0,z.P)(this.c,!0);this.xd=a};z.m.clear=function(){this.Cf.ye();this.cc={};this.Bm=[];this.di=this.Vl=null;for(this.FA=[];this.wa&&0!=this.wa.length;)this.dq(0).q()};z.m.F=function(a){IG.b.F.call(this,a);(0,z.rm)(this.c,z.Dp,this.r());this.al=this.o("fyre-stream-content");this.pj=this.o("fyre-stream-more");this.Ra.Q(this.pj);(0,z.P)(this.pj,!1)};z.m.j=function(){this.Ra&&this.Ra.q();this.Ra=null;IG.b.j.call(this)};
z.m.m=function(){IG.b.m.call(this);this.p().f(this.Ra,"showMore",this.xy)};z.m.r=function(){return{ng:z.w.P.pb,bG:!!this.Ra,l:{vA:z.W.get(z.W.e.hL)}}};z.m.yy=function(){this.Ra.vu()};z.m.Hz=function(){this.dispatchEvent({type:this.Jv,direction:this.xd,target:this,wb:(0,z.r)(this.yy,this),kk:(0,z.r)(this.CH,this)})};z.m.uq=function(){var a=this.C.lb.Sl,b=this.xd,c=a.d.u.w(),b=b===z.ks.hr,c=c.get(z.U.Sq),c=!b&&a.Bo>-c;b&&-1>a.Bo||c?this.Ra.show():this.Ra.va()};
z.m.start=function(){this.Qd||(this.Hz(),this.Qd=!0)};(0,z.u)(JG,z.sv);JG.prototype.r=function(){var a=this.k.get(z.U.de),b,c;this.k.se()?(b=z.W.get(z.W.e.SM),c=z.W.get(z.W.e.KC)):(b=z.W.get(z.W.e.hg),c=z.W.get(z.W.e.En));(0,z.wa)(b,"%s")||(b="%s "+b);(0,z.wa)(c,"%s")||(c="%s "+c);switch(a){case 1:b=(0,z.ua)(b,a);break;default:b=(0,z.ua)(c,a)}return{l:{Kw:b}}};JG.prototype.gB=function(){var a=this.c,b;b=this.r();b="\x3cspan\x3e"+(0,z.S)(b.l.Kw)+"\x3c/span\x3e";a.innerHTML=b};(0,z.u)(KG,z.xq);KG.prototype.wq=200;KG.prototype.Pi=function(){return new LG(this.Vc)};KG.prototype.r=function(){var a={};a.message=this.XA;return a};(0,z.u)(LG,z.rq);
LG.prototype.Eb=function(a,b,c){var d=(0,z.Bi)(this.element),d=new z.ef(d.width,d.height+25);b=(0,z.oq)(this.element,this.yi,a,b,d,c,9);(0,z.fi)(a.lastChild,0);b&&(d=new z.ef(0,-5),(0,z.oq)(this.element,2,a,1,d,c,5),(0,z.fi)(a.lastChild,a.offsetWidth-(this.element.offsetParent.offsetWidth-this.element.offsetLeft+this.element.offsetWidth/2)))};(0,z.u)(MG,z.T);z.m=MG.prototype;z.m.n=function(){this.c=(0,z.um)(yG,this.r())};z.m.m=function(){MG.b.m.call(this);this.Xa=new KG(this.c,this.k.get("displayName"));this.p().f(this.c,"click",this.mb)};z.m.j=function(){MG.b.j.call(this);this.Xa&&this.Xa.q()};z.m.r=function(){var a=z.oj,b={};b.Fc=this.k.get(a.cb);b.Sb=this.k.get(a.nl);b.$=this.k.get(a.aa);b.id=this.k.id;b.uU=this.k.id.replace(/[@.]/g,"-");b.Ka=this.k.get(a.Qb);return b};
z.m.mb=function(a){a.preventDefault();a.stopPropagation();this.dispatchEvent({v:this.k,type:"author_click"})};(0,z.u)(NG,z.T);z.m=NG.prototype;z.m.OC=10;z.m.j=function(){NG.b.j.call(this);delete this.Wc};z.m.O=function(){NG.b.O.call(this);this.Wc.off(null,null,this)};z.m.RG=function(a){a=new MG(a);var b=this.Te();if(b===this.OC){var c=this.dq(b-1);c&&(c.q(),b--)}0<b?this.ge(a,0,!0):this.K(a,!0)};z.m.uT=function(a){var b;this.Xc(function(c){a.id===c.k.id&&(b=c)});b&&(this.removeChild(b),b.q())};
z.m.Si=function(){this.Wc.on(this.Wc.M.Cj,this.RG,this);this.Wc.on(this.Wc.M.Fl,this.uT,this);var a=this.Wc.Zc.reverse().slice(0,this.OC);(0,z.x)(a,this.RG,this)};(0,z.u)(OG,NG);(0,z.u)(PG,z.tv);PG.prototype.F=function(a){PG.b.F.call(this,a);this.Sk()};PG.prototype.Sk=function(){this.c.innerHTML=(0,z.Ip)(this.r())};(function(a,b){function c(){var a=D.elements;return"string"==typeof a?a.split(" "):a}function d(a){var b={},d=a.createElement,f=a.createDocumentFragment,g=f();a.createElement=function(a){D.BX||d(a);var c;c=b[a]?b[a].cloneNode():k.test(a)?(b[a]=d(a)).cloneNode():d(a);return c.canHaveChildren&&!h.test(a)?g.appendChild(c):c};a.createDocumentFragment=Function("h,f","return function(){var n\x3df.cloneNode(),c\x3dn.createElement;h.shivMethods\x26\x26("+c().join().replace(/\w+/g,function(a){b[a]=d(a);g.createElement(a);
return'c("'+a+'")'})+");return n}")(D,g)}function f(a){var b;if(a.bQ)return a;if(D.AX&&!n){b=a.createElement("p");var c=a.getElementsByTagName("head")[0]||a.documentElement;b.innerHTML="x\x3cstyle\x3earticle,aside,details,figcaption,figure,footer,header,hgroup,nav,section{display:block}audio{display:none}canvas,video{display:inline-block;*display:inline;*zoom:1}[hidden]{display:none}audio[controls]{display:inline-block;*display:inline;*zoom:1}mark{background:#FF0;color:#000}\x3c/style\x3e";b=!!c.insertBefore(b.lastChild,
c.firstChild)}s||(b=!d(a));b&&(a.bQ=b);return a}var g={},h=/^<|^(?:button|form|map|select|textarea|object|iframe)$/i,k=/^<|^(?:a|b|button|code|div|fieldset|form|h1|h2|h3|h4|h5|h6|i|iframe|img|input|label|li|link|ol|option|p|param|q|script|select|span|strong|style|table|tbody|td|textarea|tfoot|th|thead|tr|ul)$/i,n,s;(function(){var c=b.createElement("a");c.innerHTML="\x3cxyz\x3e\x3c/xyz\x3e";(n="hidden"in c)&&"function"==typeof a.EU&&a.EU("#modernizr{}",function(b){b.hidden=!0;n="none"==(a.getComputedStyle?
a.getComputedStyle(b,null):b.currentStyle).display});s=1==c.childNodes.length||function(){try{b.createElement("a")}catch(a){return!0}var c=b.createDocumentFragment();return"undefined"==typeof c.cloneNode||"undefined"==typeof c.createDocumentFragment||"undefined"==typeof c.createElement}()})();var D={elements:g.elements||"abbr article aside audio bdi canvas data datalist details figcaption figure footer header hgroup mark meter nav output progress section summary time video",shivCSS:!1!==g.AX,shivMethods:!1!==
g.BX,type:"default",shivDocument:f};f(b)})(z.t.window,z.t.document);(0,z.u)(QG,z.Cv);QG.prototype.bu=function(a,b){if(!this.Pa){this.J=b;var c=b.get(z.U.$g),d=b.get(z.U.ee);this.Su=new z.zv(c,d,a.Z.ab);this.K(this.Su);this.Rr=new JG(a.u.w());this.K(this.Rr);this.Dt=null;b.xp()&&(this.nw=new HG(a),this.K(this.nw),this.Tl=new IG(a),this.K(this.Tl),xG(this.nw,{rj:this.Tl}),a.Z.readOnly=!0);this.$h=new EG(a);this.K(this.$h);this.vt((0,z.r)(function(a){this.G=a;this.K(this.G);a=this.G;this.ca&&a&&a.Q(this.Fi,!0)},this))}};
QG.prototype.r=function(){return{zK:z.w.P.YA,AK:(0,window.encodeURIComponent)(String(window.location.href)),ab:this.d.Z.ab,Dh:this.J.Dh(),se:this.J.se(),hx:!this.d.Z.Fr&&!z.w.WF,HU:this.d.Z.Fr,xp:this.J.xp()}};z.vu={LY:"fyre-archive-stream",MY:"fyre-archive-stream-header",I0:"fyre-top-content-stream",a1:"fyre-widget",Yq:"fyre-featured-content-wrapper"};(0,z.B)(z.vu,z.oC);z.m=QG.prototype;
z.m.n=function(){this.c=(0,z.um)(AG,this.r());var a=this.J.get(z.U.Kl);if(1!==a){var b=this.d.Fb,a=2===a?3:4,c=this.o("fyre-top-content-stream");(0,z.Tu)(b,a,c,this)}this.Ss.Q(this.o(z.vu.DM));this.Tl&&(b=this.o("fyre-archive-stream-header"),this.nw.Q(b),this.Tl.Q(this.o("fyre-archive-stream")));this.Rb(1)};
z.m.m=function(){QG.b.m.call(this);var a=this.G;this.ca&&a&&a.Q(this.Fi,!0);this.d.S.Fu("stream_data_received",this.oS,this);this.p().f(this,"request_content_context",this.NR).f(this,"request_content_reply",this.yT);this.Tl&&this.Tl.start()};z.m.Si=function(){this.Po&&this.Po.Si();this.Gg.Si()};z.m.oS=function(){var a=this.J,b=a.get(z.U.zl);z.Xc||b||(b=(0,z.r)(function(){this.Dt=new z.WG(this.d,a.get(z.U.ee));this.K(this.Dt,!0)},this),(0,z.qb)(z.w.P.pb+z.w.we.Dt,null,null,b))};
z.m.fH=function(a){var b=new z.Gw(this.nI,this);b.fJ=(0,z.r)(this.YW,this,a);a=(0,z.r)(function(){b.start(0,2E3)},this);(0,z.qb)(z.w.P.pb+z.w.we.vQ,null,null,a)};z.m.YW=function(a){var b=a.size;a=a.isComplete;var c=this.o("fyre-featured-content-wrapper");this.tx=new z.hE(b,a,this.d);this.K(this.tx);this.tx.Q(c);this.tx.Ag()};
z.m.vt=function(a){if(!this.d.Z.readOnly){var b=z.lv.D(),c=(0,z.r)(function(b){b=new b(this.d,{Rf:this.d.Z.Rf,dh:this.d.Z.dh,hF:this.J,Ei:this.d.Z.Ei,xt:this.J.get(z.U.Al)});a(b)},this);(0,z.mv)(b,"main",c)}};z.m.Ri=function(){0<(0,z.Vm)(this,this.G)&&(this.removeChild(this.G),this.G.q());this.vt((0,z.r)(function(a){this.G=a;this.K(this.G);a=this.G;this.ca&&a&&a.Q(this.Fi,!0)},this))};
z.m.Vi=function(a){null!=a&&(this.d.Fb.sm(1),(0,window.setTimeout)((0,z.r)(function(){this.Pa||(0,z.Dv)(this,a)},this),3E3))};z.m.NR=function(a){this.BU(a.Qr)};z.m.yT=function(a){this.BU(a.Qr,function(a){(0,z.ut)(a.Hc)})};z.m.j=function(){QG.b.j.call(this);this.J&&(this.J.off(null,null,this),this.J=null)};(0,z.u)(RG,z.Zm);RG.prototype.oe=function(a,b){a.f(b,"likeClicked",this.ES)};RG.prototype.ES=function(a){var b=z.On.D();if(z.Q.vc())b.Ca(z.W.get(z.W.e.TL)),b.open();else{var c;c=a.Dy?this.d.ya.HK:this.d.ya.Hp;var d=(0,z.r)(function(){try{c.call(this.d.ya,a.Vb)}catch(d){if("liked_own_comment"==d)b.Ca(z.W.get(z.W.e.UL)),b.open();else throw d;}},this),f=this.d.u.w();(0,z.Zl)(this.d.zb,f,d)}};(0,z.u)(SG,z.gv);z.m=SG.prototype;z.m.oe=function(a,b){SG.b.oe.call(this,a,b);a.f(b,"repliesExpanded",this.hS);a.f(b,"sortHotThreads",this.JT);a.f(b,"sortOrderChanged",this.FH);a.f(b,"sortTopComments",this.KT);a.f(b,"archiveShowMore",this.rR);a.f(b,"archiveSortOrderChanged",this.sR)};
z.m.rR=function(a){var b=a.wb||z.p;a=(0,z.r)(this.Xe,this,a.target);var c=this.d.lb;c.Sl||(c.Sl=new uG(c.C));var c=c.Sl,d=tG(c),f=c.nf[d];f&&(c.Bo=d);if(f)b(),a(f);else{c=this.d.lb.nm();d=c.g.jg;if(c.get(d))b();else c.on(c.kb(d),b,this);(0,z.hv)(this,c,a)}};z.m.cy=function(a,b){var c=2===b.Fd,d=1!==b.Fd;switch(b.type){case 0:var f=this.d.u.w(),f=(0,z.Lj)(b,f),g=f.get(z.Yj),g=this.d.u.eb().get(g);f.set(z.Mj,g);a.py(f,c,d)}};
z.m.Ks=function(a){if(1!==this.bo){var b=this.RX.$h;b.oj(!1);GG(b,b.qn);(0,z.B)(a,{direction:z.ks.Hd,wb:z.p});this.FH(a)}};z.m.sR=function(a){(0,z.iv)(this);a.rj.qo(a.direction);var b=this.d.lb.nm(a.direction,!0),c=(0,z.r)(function(b){a.wb();this.Xe(a.rj,b)},this);(0,z.hv)(this,b,c,a.kk)};z.m.FH=function(a){var b=(0,z.kv)(this,1);(0,z.zs)(this.d.lb);b.qo(a.direction);var c=this.d.lb.Ni(a.direction==z.ks.Hd?this.d.lb.Fb.Xb:0),d=(0,z.r)(function(c){a.wb();this.Xe(b,c)},this);(0,z.hv)(this,c,d,a.kk)};
z.m.KT=function(a){var b=(0,z.kv)(this,3),c=this.d.lb.Li("likes");(0,z.hv)(this,c,(0,z.r)(function(c){a.wb();(0,z.$a)(c)?(0,z.gu)(b):this.Xe(b,c)},this))};z.m.JT=function(a){var b=(0,z.kv)(this,4),c=this.d.lb.Oi();(0,z.hv)(this,c,(0,z.r)(function(c){a.wb();(0,z.$a)(c)?(0,z.gu)(b):this.Xe(b,c)},this))};
z.m.hS=function(a){var b=a.s,c=z.jk;if(!b.get("hasBeenExpanded")){b.set("expanding",!0);var d=function(){b.set(c,a.vn.be)},f=(0,z.r)(function(f){b.set(c,a.vn.be,!1);b.set("hasBeenExpanded",!0);b.set("expanding",!1);(0,z.A)(f,(0,z.pa)(this.cy,a.JP),this);this.Ba.f(a.vn,"threadVisChanged",d)},this),g=wG(this.d.lb,b);g.on(g.M.Gn,f,this);f(g.get(g.g.sf))}};(0,z.u)(TG,z.yp);z.m=TG.prototype;z.m.c=null;z.m.j=function(){TG.b.j.call(this);this.Eu.q();this.lF.q();this.Cc.q();this.eg&&this.eg.q();delete this.eg};z.m.Fm=function(a){TG.b.Fm.call(this,a);this.Eu=new SG(this.d);this.Eu.handle(a);this.lF=new RG(this.d);this.lF.handle(a)};z.m.MA=function(){this.d.bl.stop()};z.m.WX=function(){this.d.Jp.stop()};z.m.Yk=function(){this.d.bl.start()};z.m.TX=function(){this.d.Jp.start()};
z.m.ta=function(){this.eg&&this.eg.q();this.Cc.ta(this.c);var a=(0,z.Ap)();this.Cc.Vi(a);this.d.S.L("render_complete")};(0,z.u)(UG,z.Bk);UG.prototype.mE=CG.D();UG.prototype.j=function(){UG.b.j.call(this);this.stop();delete this.Z;delete this.oa;VG(this);(0,z.Gk)(this);this.jk&&(this.jk.q(),delete this.jk)};UG.prototype.TA=function(){this.stop();VG(this);UG.b.TA.call(this)};z.Wb.main.zi.la(UG);})(fyre.conv);
