(function(z){
var nH=function(a,b){(0,z.Ff)(a.element,(0,z.Oi)(b))};var oH=function(a){return null!==(0,z.mg)(a.element,function(a){return a instanceof window.Element||(0,z.q)(a.className)?(0,z.wa)(a.className,"fyre-editor-container"):!1},!0,10)};var pH=function(a){var b=[];a=(0,z.nf)(window.document,"a",null,a.element);for(var c=0;c<a.length;c++)b.push(a[c]);return new z.Ni(b)};var qH=function(a,b){return(0,z.af)(a.element,b)};
var rH=function(a){(0,z.zi)(a,!1);if(z.uC){var b=a;for(a=a.parentNode;a&&"HTML"!=a.tagName;){if(z.Ai?"none"==a.style[z.Ai].toLowerCase():(z.F||z.C)&&"on"==a.getAttribute("unselectable")){(0,z.zi)(a,!1,!0);for(var c=0,d=a.childNodes.length;c<d;c++){var f=a.childNodes[c];f!=b&&1==f.nodeType&&(0,z.zi)(a.childNodes[c],!0)}}b=a;a=a.parentNode}}};var sH=function(a){var b=a.target.tagName;"TEXTAREA"!=b&&"INPUT"!=b&&a.preventDefault()};
var tH=function(a,b){z.uC&&b.f(a,"mousedown",sH,!0);(0,z.zi)(a,!0);for(var c=a.getElementsByTagName("INPUT"),d=0,f=c.length;d<f;d++){var g=c[d];g.type in z.IC&&rH(g)}(0,z.x)(a.getElementsByTagName("TEXTAREA"),rH)};var uH=function(){return'\x3cspan class\x3d"fyre-editor-spinner"\x3e\x3c/span\x3e'};var vH=function(a,b){z.Br.set(a,(0,z.Oa)((0,z.rg)(b)),600,void 0,void 0,void 0)};var wH=function(a){return a};
var xH=function(a){var b;if(b&&48<a.length)48<b&&(b=48),a=a.substring(0,48-b)+"..."+a.substring(a.length-b);else if(48<a.length){b=Math.floor(24);var c=a.length-b;a=a.substring(0,b+0)+"..."+a.substring(c)}return a};var yH=function(a,b){z.Sk.call(this,a,b)};var zH=function(a,b){this.vd=a;this.Lz=new z.Rp(b);this.K(this.Lz);z.T.call(this,b)};var AH=function(){};var BH=function(a){this.k=a;this.k.bind("change",this.ta,this);this.k.bind("visible",this.N,this);CH.call(this);this.lA((0,z.po)("fyre-mention-item"))};
var DH=function(a,b){z.cC.call(this,AH.D(),null);this.MP=b;this.k=a;this.Rc=this.k.get(a.g.Mj);this.ij={};this.Od={};this.iq={};this.Tk={};this.nJ=null;(0,z.x)(this.lr,this.Oy,this);this.Sj(this.bh.Ej,a.get(a.g.Pn));this.Sj(this.bh.Ej,a.get(a.g.av));this.Sj(this.bh.$n,a.get(a.g.nr));this.k.on(this.k.kb(this.k.g.wf),this.op,this)};
var EH=function(a,b,c){var d=c.get(c.g.Sc);a.iq[d]=b;!a.ca||a.ap()[b].length>=a.mr[b]||!a.Np(c)?a.Od[b][d]=c:(0,z.oe)(a.ij[b],d)&&(d=new BH(c),c.get(c.g.ce)&&d.N(!1),d.on(d.M.Uq,(0,z.r)(a.L,a,a.M.Uq)),a.ge(d,a.Ox(b),!0),a.dg&&a.dg[b].push(d))};var FH=function(){};var GH=function(a){z.Gh.call(this);this.Qq=a||window;this.rt=(0,z.qh)(this.Qq,"resize",this.wy,!1,this);this.Wb=(0,z.rf)(this.Qq)};
var HH=function(a,b){z.Gh.call(this);this.U=(0,z.O)(a);this.bb=new z.Mm(this);this.lB=new GH(this.U.ba());this.Cd={};this.Kd=this.U.n("DIV",{className:IH});(0,z.P)(this.Kd,!1);a.appendChild(this.Kd);(0,z.Zh)(this.Kd,"zIndex",b);this.po=this.Kd;this.dF=this.U.n("DIV",{className:"tr_bubble_closebox",innerHTML:"\x26nbsp;"});this.po.appendChild(this.dF);tH(this.Kd,this.bb);this.mc=new z.un(this.Kd)};var JH=function(a,b){return(0,z.he)(a.Cd,function(a){return a.type==b})};
var KH=function(a,b,c,d){var f=null,g;for(g in a.Cd){var h=a.Cd[g].SA;if(!f||(0,z.Sf)(h,f))f=a.Cd[g].SA}return(0,z.oq)(f,b,a.Kd,c,null,LH,d)};var MH=function(a,b,c,d,f,g){this.type=c;this.SA=f;this.yW=g;this.element=a.n("DIV",{className:"tr_bubble_panel",id:b},a.n("DIV",{className:"tr_bubble_panel_title"},d+":"),a.n("DIV",{className:"tr_bubble_panel_content"}))};var NH=function(){z.Fv.call(this);this.Lc=new z.Mm(this)};var OH=function(a,b){return new HH(a,b)};
var PH=function(a){var b=a.k1||a.t.Rl.document.body;a.U=(0,z.O)(b);var c=QH[a.t.id];c||(c=OH.call(null,b,a.t.i1||0),QH[a.t.id]=c);return c};var RH=function(a){if(a.ej){var b=PH(a),c=a.ej;(0,z.Gf)(b.Cd[c].element);delete b.Cd[c];c=(0,z.Va)(b.Cd);1>=c&&(0,z.Xe)(b.Kd,"tr_multi_bubble");0==c?b.fF():b.Eb();a.zH()}};
var SH=function(a,b,c,d,f){c=a.U.n("SPAN",{className:"tr_bubble_link"},c);a.$y&&c.setAttribute("tabindex",0);c.setAttribute("role","link");f?f.appendChild(c):(f=a.U.h(b))&&(0,z.Hf)(c,f);c.id=b;tH(c,a.Lc);d&&(a=a.Lc,TH.f(c,d,void 0,a.Ba||a,a))};var UH=function(a){NH.call(this);this.ms=(0,z.Ha)(arguments);this.ur=[];this.kX=["http","https","ftp"]};var VH=function(a){return a.dl.getAttribute("href")||""};
var WH=function(a){var b,c=VH(a);a.LU(c)?(c=(0,z.J)("invalid url"),b=!0):c&&(0,z.sa)(c,"mailto:")&&(c=c.substring(7));return{qt:c,valid:!b}};var XH=function(a,b){var c=(0,z.Bb)(b)[1]||null||"http";return(0,z.hd)(a.kX,c.toLowerCase())};var YH=function(){UH.call(this)};var ZH=function(a,b,c){this.hd=null;this.k=a;this.R=b;this.mc=c;z.Fv.call(this)};var $H=function(a){a.hd.parentNode&&aI(a,a.hd,!0);(0,z.op)(a.R);a.vo()};
var aI=function(a,b,c){(0,z.He)(c)&&c&&z.I?(a=a.t.Qa.n("SPAN","fyre-mention-space","\u00a0"),(0,z.Ef)(a,b),(0,z.fx)(a,!1),(0,z.Gf)(a)):(0,z.fx)(b,!1)};var bI=function(a){var b=!1;a.R.Xc(function(a){b=b||!(0,z.pp)(this.R,a)&&a.ma()},a);return b};var cI=function(a,b){this.hb(a||{});z.Gr.call(this,b)};
var dI=function(a,b){var c=a.H.Qa.sa(),d=c.createElement("style");d.setAttribute("type","text/css");d.styleSheet?d.styleSheet.cssText=b:d.appendChild(c.createTextNode(b));var f=c.head;f||(f=c.createElement("head"),c.appendChild(f));f.appendChild(d)};var eI=function(a,b){var c="";(0,z.A)(b,function(a,b){c+=(0,z.ua)("%s:%s !important;",b,a)});dI(a,(0,z.ua)("body { %s }",c))};
var fI=function(a,b){var c=(new z.Ni(a.H.h())).mt(),c=!c.element||(0,z.id)(c.element)&&!c.element.length?a.xk.height:(0,z.li)(c.element).y+c.element.offsetHeight+10;(0,z.si)(a.Zb.element,Math.max(a.xk.height,Math.min(a.ga[a.ga.e.fr],c+(b||0))))};
var gI=function(a,b){a.Jh=new DH(a.B,a.ga);a.Jh.Be(!0);a.Jh.on(a.Jh.M.Uq,function(a,b){b.preventDefault();b.stopPropagation();this.H.execCommand("+mention",a)},a);a.rr[a.ob.Je]=hI(a,b,null,(0,z.r)(function(a){if(!a.h()){this.Jh.ta();var b=this.Jh.h();(0,z.P)(b,void 0);this.Vg.append(b);a.qq(b)}},a));a.Jh.on(a.Jh.M.xl,(0,z.r)(function(){this.L(this.M.xl)},a),a)};
var hI=function(a,b,c,d){var f;c&&((0,z.P)(c,void 0),a.Vg.append(c));f=new z.vq(c,new z.rq(b.h(),1));(0,z.vn)(f);f.Uk(!0);a.p().f(b,"action",function(){var a=new z.Ni(b.c);f.Hh||150>(0,z.Kd)()-f.Fp?(0,z.Ri)(a,"fyre-button-left-open"):(0,z.Qi)(a,"fyre-button-left-open");f.N(!(f.Hh||150>(0,z.Kd)()-f.Fp))});a.p().f(f,"beforeshow",function(){d&&d(f);iI(this)});a.p().f(f,"beforehide",function(){(0,z.Ri)(new z.Ni(b.c),"fyre-button-left-open")});return f};var iI=function(a){(0,z.A)(a.rr,function(a){a.N(!1)})};
var jI=function(a){(0,z.qh)(a.H,"focus",(0,z.r)(function(){kI(this,!1)},a));(0,z.qh)(window.document,"click",(0,z.r)(function(a){oH(new z.Ni(a.target))||kI(this,!0)},a))};var kI=function(a,b){var c=new z.Ni(a.Gi);b?(vH(a.Bu,a.G.dA()),a.Ce(!1,a.ga[a.ga.e.VC]),(0,z.Qi)(c,"fyre-editor-minimal"),a.I1()):(a.Kp(),a.H.focus(),(0,z.Ri)(c,"fyre-editor-minimal"))};var lI=function(a,b){this.gg=mI;this.M=nI;this.ob=oI;this.hb(a||{});z.Gr.call(this,b)};
var pI=function(a){for(var b=a.UA.element.value.split("@"),c=1,d=b.length;c<d;c++){var f=b,g=c,h;var k=a;h=b[c];for(var n=void 0,s=void 0,D=void 0,v=0,G=h.length;v<G;v++){var K=k,E=h.substring(0,v+1),s=K.B.get(K.B.g.Pn),L=K.B.get(K.B.g.nr),K=(0,z.r)(K.fV,K,E);if(s=s&&s.find(K)||L&&L.find(K))n=s,D=v}n?(k=n.Iq(),k.set(k.g.jr,""),h=(0,z.bn)(k.toJSON())+h.substring(D+1)):h="@"+h;f[g]=h}a=(0,z.Be)("\x3cp\x3e",b.join(""),"\x3c/p\x3e");return a=a.replace(/(\r\n|\r|\n)/g,"\x3c/p\x3e\x3cp\x3e")};
var qI=function(a,b){b=(0,z.va)(b);b=b.replace(/(<([^>]+)>)/ig,"").replace(/<\/p>\s*<p>/g,"\r\n");a.UA.element.value=b};var rI=function(){};var sI=function(a,b,c){z.vo.call(this,a,b||rI.D(),c);(0,z.xo)(this,!1);this.mn(!0);a||this.Vk("")};var tI=function(a){return a.Tp.top+a.Tp.bottom+a.NE.top+a.NE.bottom};var uI=function(a){var b=a.Ek,c=a.h();b&&c&&a.Bt&&(b-=tI(a));return b};var vI=function(a){var b=a.hV,c=a.h();b&&c&&a.Bt&&(b-=tI(a));return b};
var wI=function(a){if(!a.NH){var b=a.h().cloneNode(!1);(0,z.Zh)(b,{position:"absolute",height:"auto",top:"-9999px",margin:"0",padding:"1px",border:"1px solid #000",overflow:"hidden"});a.X().sa().body.appendChild(b);var c=b.scrollHeight;b.style.padding="10px";var d=b.scrollHeight;a.Yz=d>c;b.style.borderWidth="10px";a.Xz=b.scrollHeight>d;b.style.height="100px";100!=b.offsetHeight&&(a.Bt=!0);(0,z.Gf)(b);a.NH=!0}var b=a.h(),c=a.h().scrollHeight,f=a.h(),d=f.offsetHeight-f.clientHeight;if(!a.Yz)var g=a.Tp,
d=d-(g.top+g.bottom);a.Xz||(f=(0,z.oi)(f),d-=f.top+f.bottom);c+=0<d?d:0;a.Bt?c-=tI(a):(a.Yz||(d=a.Tp,c+=d.top+d.bottom),a.Xz||(a=(0,z.oi)(b),c+=a.top+a.bottom));return c};var xI=function(a,b){a.Ui!=b&&(a.Ui=b,a.h().style.height=b+"px")};var yI=function(a){a=a.h();a.style.height="auto";var b=a.value.match(/\n/g)||[];a.rows=b.length+1};z.vt=function(a,b){this.C=a;this.hb(b);z.Gr.call(this)};
var zI=function(a,b){var c=b.g;b.get(c.Hb);b.By(c.Pn)||b.set(c.Pn,a.C.u.Nc());b.By(c.nr)||b.set(c.nr,a.C.zb.ys());b.By(c.av)||b.set(c.av,a.C.u.eb());(0,z.Rg)(z.Q,z.Q.g.fa,a.yg,a);a.B.set(b.g.wf,z.Q.id)};
var AI=function(a){if(!a.Fh&&a.G&&a.G.um()){var b=a.C.u.w(),c=z.Q.get(z.Qk.rc),c=c&&b.get(b.g.gc),b=a.Yt.getParent()==a.G.um(),d=a.Vs.h();if(c&&!b){a:{var f=a.G,g=a.Yt,h=a.G.Uc[a.G.ob.Je],k=0;if(h){k=(0,z.Vm)(f.toolbar,h);if(-1==k)break a;k++}f.toolbar.ge(g,k,!0)}d||(a.Vs.ta(),a.U.$W(a.Vs.h(),a.o(a.gg.HL)))}!c&&b&&(a.G.um().removeChild(a.Yt,!0),d&&(0,z.P)(d,!1))}};var BI=function(a){z.T.call(this,a)};z.ov=function(a,b){z.vt.call(this,a,b)};z.vo.prototype.lj=(0,z.jd)(39,function(a){this.Ca(a)});
z.gz.prototype.lj=(0,z.jd)(38,(0,z.ba)());z.Ey.prototype.kA=(0,z.jd)(30,function(a){a!=this.Ek&&(this.Ek=a,this.Gb()&&(0,z.Gy)(this))});z.by.prototype.hu=(0,z.jd)(24,function(){var a=this.yc;if(a){var b=(0,z.ty)(this);b&&(0,z.Hf)(a,b)}});z.Ey.prototype.hu=(0,z.jd)(23,function(){this.Gb()&&(0,z.Gf)((0,z.ty)(this))});z.HA.prototype.um=(0,z.jd)(18,(0,z.e)("Ta"));z.nh.prototype.rm=(0,z.jd)(4,function(a,b){var c=this.ac[a],d=[];if(c)for(var f=0;f<c.length;++f){var g=c[f];g.capture==b&&d.push(g)}return d});
z.Gh.prototype.rm=(0,z.jd)(3,function(a,b){return this.Re.rm(a,b)});var CI=/^[\w-]+(\.[\w-]+)*\@([\w-]+\.)+(\d+|\w\w+)$/i;(0,z.u)(yH,z.Tk);yH.prototype.hb=function(a,b){this.view=b;yH.b.hb.call(this,a,b);var c=this.C.u.Nc();c.on(c.M.Cj,(0,z.pa)(this.gp,!0),this);c.on(c.M.Fl,(0,z.pa)(this.gp,!1),this);z.Q.on(z.Q.M.Ie,this.dU,this)};yH.prototype.j=function(){this.C.u.Nc().off(null,null,this);z.Q.off(null,null,this);yH.b.j.call(this)};yH.prototype.$S=function(){var a=this.view;vH(a.Bu,a.G.dA())};(0,z.yg)(["window_nav"],yH.prototype.$S,z.$i);z.m=yH.prototype;
z.m.dU=function(a){a=this.C.u.yk(a.id);this.view.B.set("following",a)};z.m.gp=function(a,b){b.id===z.Q.id&&this.view.B.set("following",a)};z.m.GP=function(){this.view.clear()};z.m.FP=function(a){this.view.Vh(a.error_type)};z.m.SW=function(){this.view.ju()};(0,z.yg)(["user_logged_in"],yH.prototype.SW,z.$i);(0,z.u)(zH,z.T);z.m=zH.prototype;z.m.n=function(){var a;a=z.tp.Xm({JE:!0});a=(0,z.zf)(this.U.Ia,a);this.F(a)};z.m.F=function(a){this.c=a;a=this.U.o("fyre-comment",this.c);this.Lz.ta(a);this.Iw=this.U.o("fyre-icon-remove",this.c);this.KK()};z.m.m=function(){zH.b.m.call(this);(0,z.Rg)(this.vd,this.vd.g.gc,this.KK,this);this.p().f(this.Iw,"click",(0,z.pa)(this.dispatchEvent,"canceled"))};z.m.O=function(){zH.b.O.call(this);this.vd.off(null,null,this)};
z.m.KK=function(){var a=this.vd.get(this.vd.g.gc);a?(this.Lz.Ca(a.body),(0,z.P)(this.c,!0)):(0,z.P)(this.c,!1)};(0,z.u)(AH,z.Ko);(0,z.Ie)(AH);AH.prototype.T=(0,z.l)("fyre-mention-menu");var CH=(0,z.Er)(z.vo);(0,z.u)(BH,CH);var DI=BH.prototype.M={Uq:"clicked"};z.m=BH.prototype;z.m.Rb=function(){BH.b.Rb.call(this);this.ta()};z.m.If=function(){return this.k.get(this.k.g.aa)};z.m.Ca=function(){return this.k.get(this.k.g.aa)};z.m.m=function(){BH.b.m.call(this);this.p().f(this,"action",(0,z.r)(this.L,this,this.M.Uq,this.k))};z.m.O=function(){this.k.off(null,null,this);BH.b.O.call(this)};z.m.r=function(){var a=z.ij;return{Fc:this.k.get(a.cb),$:this.k.get(a.aa),zc:this.k.get(a.xb)}};
z.m.ta=function(){this.k&&this.pa.$e((0,z.go)(this.r()))};z.m.N=function(a,b){this.da&&BH.b.N.call(this,a,b)};(0,z.u)(DH,z.cC);DH.prototype.bh={Ej:"conv",ce:"custom",$n:"soc"};var EI={},FI=DH.prototype.bh;EI[FI.Ej]=10;EI[FI.ce]=2;EI[FI.$n]=10;DH.prototype.mr=EI;var GI=DH.prototype.bh;DH.prototype.lr=[GI.Ej,GI.$n,GI.ce];var HI=DH.prototype.bh,II={};II[HI.Ej]="";II[HI.ce]="";II[HI.$n]="";DH.prototype.FN=II;var JI=DH.prototype.M={xl:"fetchFriends",lC:"fetchFriendsComplete"};(0,z.B)(JI,DI);z.m=DH.prototype;z.m.Sj=function(a,b){b.on(b.M.Cj,(0,z.r)(this.nE,this,a));b.forEach((0,z.r)(this.nE,this,a))};
z.m.Pw=function(){var a=z.ij,b=z.jj;this.Ak=new z.hj((0,z.Yd)(a.xb,b.Un,a.Sc,"custom@livefyre.com",a.ce,!0));this.fl=new z.hj((0,z.Yd)(a.xb,b.Ib,a.Sc,"custom@twitter.com",a.ce,!0));EH(this,this.bh.ce,this.fl);EH(this,this.bh.ce,this.Ak)};z.m.Oy=function(a){var b=new z.vo(this.FN[a]);b.oc(!1);this.ij[a]=[];this.Od[a]={};this.Tk[a]=b;this.Nk||(this.Nk={});this.Nk[(0,z.Qm)(b)]=!0};z.m.nE=function(a,b){var c=b.get(b.g.aa);(0,z.Jd)(c)||b instanceof z.nj&&b.Eg()||EH(this,a,b.Iq())};
z.m.Rb=function(){DH.b.Rb.call(this);(0,z.$a)(this.Rc.get(this.Rc.g.Gd))||(nH(this.pa,(0,z.Ti)((0,z.fo)(this.r()))),(0,z.Qi)(this.pa,"fyre-mention-connections"),this.ay(),this.Rc.on(this.Rc.kb(this.Rc.g.Gd),this.ay,this));(0,z.x)(this.lr,function(a){this.K(this.Tk[a],!0)},this);this.Pw();this.lk()};z.m.Mw=function(a){a.preventDefault();a.stopPropagation();var b=(0,z.Nl)(a.target.href,{height:400,width:770});this.nJ=new z.lo(b,(0,z.r)(this.LR,this,a.target.name),16E4);this.nJ.start()};z.m.r=function(){return{l:{yt:this.MP[z.X.pv]}}};
z.m.LR=function(a){this.L(this.M.xl);(0,z.Qi)((0,z.Ui)(this.pa,"fyre-provider-"+a),"fyre-provider-fetching")};z.m.op=function(){if((this.Rc=this.k.get(this.k.g.Mj))&&this.Rc.id)this.Rc.on(this.Rc.kb(this.Rc.g.Gd),this.ay,this)};
z.m.ay=function(){if(this.pa){var a=(0,z.Ui)(this.pa,"fyre-provider-connections"),b=this.Rc.get(z.Qk.Gd);(0,z.$a)(b)?(a&&a.remove(),(0,z.Ri)(this.pa,"fyre-mention-connections")):((0,z.Qi)(this.pa,"fyre-mention-connections"),a||(a=(0,z.Ti)((0,z.fo)(this.r())),nH(this.pa,a)),pH(a).remove(),(0,z.A)(b,function(b,d){var f=(0,z.Ti)("a",{"class":"fyre-provider-connect fyre-provider-"+d,href:b,name:d});a.append(f);this.p().f(f.element,"click",(0,z.r)(this.Mw,this))},this))}};
z.m.Ox=function(a){return(a=this.lr[(0,z.dd)(this.lr,a)+1])?(0,z.dd)(this.wa,this.Tk[a]):this.wa.length};z.m.lk=function(a){this.dg=null;this.zx(a);DH.b.lk.call(this,a);(0,z.A)(this.ap(),this.Ax,this)};z.m.zx=function(a){var b=z.ij,c=(0,z.q)(a)?a.split(" ")[0]:"";this.fl.set((0,z.Yd)(b.aa,c,b.gi,c));this.Ak.set((0,z.Yd)(b.aa,c));""===a&&(this.fl.L("visible",!1),this.Ak.L("visible",!1))};
z.m.Ax=function(a,b){for(var c=a.length,d,f,g;c>this.mr[b];)d=this.removeChild(a.pop()),f=d.k,g=f.get(f.g.Sc),(0,z.ne)(this.ij[b],g),this.Od[b][g]=f,d.q(),c--;c<this.mr[b]&&(0,z.he)(this.Od[b],function(a,d){this.Np(a)&&(EH(this,b,a),(0,window.setTimeout)((0,z.r)(function(){delete this.Od[b][d]},this),50),c++);return c>=this.mr[b]},this)};z.m.Np=function(a){var b;(b=!this.km)||(a=a.get(a.g.aa),b=this.km,b=0==(0,z.Id)(b,a.substr(0,b.length)));return b};
z.m.ap=function(){var a={},b;if(this.dg)return this.dg;(0,z.A)(this.bh,function(b){a[b]=[]});this.Xc(function(c){c.ma()&&!(0,z.pp)(this,c)&&(b=c.k,a[this.iq[b.get(b.g.Sc)]].push(c))},this);return this.dg=a};var TH=new FH,KI=["click",z.H?"keypress":"keydown","keyup"];FH.prototype.f=function(a,b,c,d,f){function g(a){"click"==a.type&&(0,z.fh)(a)?b.call(d,a):13!=a.keyCode&&3!=a.keyCode||"keyup"==a.type?32==a.keyCode&&"keyup"==a.type&&"button"==(a.target.getAttribute("role")||null)&&(b.call(d,a),a.preventDefault()):(a.type="keypress",b.call(d,a))}g.bj=b;g.mX=d;f?f.f(a,KI,g,c):(0,z.qh)(a,KI,g,c)};
FH.prototype.$a=function(a,b,c,d,f){for(var g,h=0;g=KI[h];h++){var k;var n=a;k=g;var s=!!c;k=(0,z.ih)(n)?n.rm(k,s):n?(n=(0,z.th)(n))?n.rm(k,s):[]:[];for(n=0;s=k[n];n++)if(s.Td.bj==b&&s.Td.mX==d){f?f.$a(a,g,s.Td,c,d):(0,z.Bh)(a,g,s.Td,c,d);break}}};(0,z.u)(GH,z.Gh);z.m=GH.prototype;z.m.rt=null;z.m.Qq=null;z.m.Wb=null;z.m.Rx=function(){return this.Wb?this.Wb.Oa():null};z.m.j=function(){GH.b.j.call(this);this.rt&&((0,z.Ch)(this.rt),this.rt=null);this.Wb=this.Qq=null};z.m.wy=function(){var a=(0,z.rf)(this.Qq);a==this.Wb||a&&this.Wb&&a.width==this.Wb.width&&a.height==this.Wb.height||(this.Wb=a,this.dispatchEvent("resize"))};(0,z.u)(HH,z.Gh);var IH="tr_bubble";z.m=HH.prototype;z.m.od=null;z.m.j=function(){HH.b.j.call(this);(0,z.Gf)(this.Kd);this.Kd=null;this.bb.q();this.bb=null;this.lB.q();this.lB=null};z.m.Aa=(0,z.e)("po");z.m.Cb=(0,z.e)("Kd");z.m.jU=function(){this.ma()&&this.Eb()};z.m.fF=function(){this.mc.N(!1)};z.m.jT=function(){for(var a in this.Cd)(0,z.Gf)(this.Cd[a].element);this.Cd={};(0,z.Xe)(this.Kd,"tr_multi_bubble");this.bb.Wd();this.dispatchEvent("hide")};z.m.ma=function(){return this.mc.ma()};
var LI=z.F?4:2,LH=new z.Xh(LI,0,LI,0);HH.prototype.Eb=function(){var a=null,b=!0,c;for(c in this.Cd)var d=this.Cd[c],a=d.SA,b=b&&d.yW;c=496;a=(0,z.mi)(this.Kd)!=(0,z.mi)(a);b&&(c=KH(this,a?7:5,4,9));c&496&&(c=KH(this,a?6:4,5,9));c&496&&KH(this,a?7:5,4,5)};MH.prototype.Aa=function(){return this.element.lastChild};(0,z.u)(NH,z.Fv);var QH={};z.m=NH.prototype;z.m.ej=null;z.m.$y=!1;z.m.We=(0,z.cb)("AbstractBubblePlugin");z.m.sk=function(){this.ma()&&this.Ti();return!1};
z.m.Ti=function(a,b){var c;if(a)c=a.target;else if(b)c=b;else{var d=this.t.Fa();if(d){var f=d.ha(),g=d.Ha(),h=d.Ja(),k=d.rb();z.F&&d.isCollapsed()&&f!=g&&(d=(0,z.Ew)(f,h));1==f.nodeType&&f==g&&h==k-1&&(f=f.childNodes[h],1==f.nodeType&&(c=f))}c=c||d&&d.Cb()}a:{if(c&&(c=this.FG(c))){c==this.dl&&this.ej||(this.ej&&RH(this),this.Wr(c));c=!1;break a}this.ej&&RH(this);c=!1}return c};z.m.disable=function(a){if(a.Hg==z.iy){var b=QH[a.id];b&&(b.q(),delete QH[a.id])}};
z.m.Wr=function(a){var b=PH(this);if(!JH(b,this.Fx())){this.dl=a;var c=this.Fx(),d=this.GG(),f=(0,z.r)(this.zF,this),g=this.DX(),h=(0,z.ze)();a=new MH(b.U,h,c,d,a,!g);b.Cd[h]=a;for(var k,d=0,g=b.po.childNodes.length-1;d<g;d++){var n=b.po.childNodes[d];if(b.Cd[n.id].type>c){k=n;break}}(0,z.Df)(a.element,k||b.po.lastChild);f(a.Aa());tH(a.element,b.bb);c=(0,z.Va)(b.Cd);1==c?(b.bb.f(b.dF,"click",b.fF).f(b.lB,"resize",b.jU).f(b.mc,"hide",b.jT),b.mc.N(!0),b.Eb()):2==c&&(0,z.N)(b.Kd,"tr_multi_bubble");b.Eb();
this.ej=h;this.Lc.f(b,"hide",this.zH);this.Nh();this.$y&&this.Lc.f(b.Aa(),"keydown",this.JV)}};z.m.Fx=(0,z.l)("");z.m.GG=(0,z.l)("");z.m.DX=z.Ac;z.m.Nh=z.p;z.m.zH=function(){this.ej=this.dl=null;this.Lc.Wd()};z.m.hp=function(a){if(this.$y&&this.ma()&&9==a.keyCode&&!a.shiftKey){var b=PH(this).Aa();if(b=(0,z.of)("tr_bubble_link",b))return b.focus(),a.preventDefault(),!0}return!1};
z.m.JV=function(a){if(this.ma()&&9==a.keyCode){var b=PH(this).Aa(),b=(0,z.mf)("tr_bubble_link",b);if(a.shiftKey?b[0]==a.target:b.length&&b[b.length-1]==a.target)this.t.focus(),a.preventDefault()}};z.m.ma=function(){return!!this.ej};z.m.Eb=function(){var a=PH(this);a&&a.Eb()};z.m.zo=function(a){return this.U.n("SPAN",{id:a,className:"tr_option-link"},this.U.createTextNode("\u00a0-\u00a0"))};(0,z.u)(UH,NH);var MI=(0,z.J)("Go to link: "),NI=(0,z.J)("Change"),OI=(0,z.J)("Remove");z.m=UH.prototype;z.m.XX=!1;z.m.dP=!0;z.m.We=(0,z.l)("LinkBubble");z.m.Gh=function(a){return"updateLinkBubble"==a};z.m.vg=function(a){"updateLinkBubble"==a&&(a=this.dl,RH(this),this.Wr(a))};z.m.FG=function(a){a=(0,z.lg)(a,"A");if(!a){var b=this.t.Fa();b&&b.isCollapsed()&&0==b.Ja()&&(b=b.ha().previousSibling)&&"A"==b.tagName&&(a=b)}return a};z.m.Fx=(0,z.l)("A");z.m.GG=function(){return z.VC};
z.m.zF=function(a){var b=WH(this),c=b.valid?"black":"red",d=!this.dP||XH(this,b.qt);if(!CI.test(b.qt)&&b.valid&&d){var f=this.U.n("SPAN",{id:"tr_test-link-span"},MI),c=this.U.n("SPAN",{id:"tr_link-text",style:"color:"+c},""),b=xH(b.qt);SH(this,"tr_test-link",this.U.createTextNode(b).data,this.bY,c)}else c=this.U.n("SPAN",{id:"tr_link-text",style:"color:"+c},this.U.createTextNode(b.qt));d=this.zo("tr_change-link-span");SH(this,"tr_change-link",NI,this.GX,d);this.ur=[];for(b=0;b<this.ms.length;b++){var g=
this.ms[b],h=this.zo(g.SX);this.ur.push(h);SH(this,g.L1,g.II,function(){g.f1(VH(this))},h)}h=this.zo("tr_delete-link-span");SH(this,"tr_delete-link",OI,this.Yw,h);this.Nh();f=this.U.n("DIV",{id:"tr_link-div"},f||"",c,d);for(b=0;b<this.ur.length;b++)f.appendChild(this.ur[b]);f.appendChild(h);a.appendChild(f)};z.m.bY=function(){var a;a=VH(this);a=this.cY?this.cY(a):a;(0,z.Nl)(a,{target:"_blank",noreferrer:this.XX},this.t.Rl)};z.m.LU=z.Ac;
z.m.GX=function(a){a.preventDefault();this.t.execCommand("link",new z.aA(this.dl,!1));RH(this)};z.m.Yw=function(){this.t.fk();var a=this.dl,b=a.lastChild;(0,z.If)(a);(0,z.fx)(b,!1);RH(this);this.t.rh();this.t.focus()};z.m.Nh=function(){if(this.U.h("tr_link-div")){var a=this.U.h("tr_test-link-span");if(a){var b=VH(this);(0,z.P)(a,!(b&&(0,z.sa)(b,"mailto:")))}for(a=0;a<this.ms.length;a++){var b=this.ms[a],c=this.U.h(b.SX);c&&(0,z.P)(c,b.i2(VH(this)))}}};(0,z.u)(YH,UH);z.m=YH.prototype;z.m.Wr=function(a){qH(new z.Ni(a),"fyre-mention")&&YH.b.Wr.call(this,a)};z.m.zF=function(a){var b=this.U.n("DIV",{id:"tr_link-div"}),c=this.zo("tr_delete-link-span");SH(this,"tr_delete-link",OI,this.Yw,c);this.Nh();b.appendChild(c);a.appendChild(b)};z.m.FG=function(a){if("A"==a.tagName&&(0,z.af)(a,"fyre-mention"))return a};z.m.zo=function(a){return this.U.n("SPAN",{id:a,className:"tr_option-link"})};z.m.Yw=function(){(new z.Ni(this.dl)).remove();RH(this);this.t.rh()};
z.m.We=(0,z.l)("MentionBubble");(0,z.u)(ZH,z.Fv);z.m=ZH.prototype;z.m.We=(0,z.cb)("+mention");z.m.Gh=function(a){return"+mention"==a};z.m.Ti=function(){var a=this.t.Fa(),b;(b=a?a.Cb():null)&&"SPAN"==b.tagName&&(0,z.af)(b,"fyre-mention-partial")?(this.hd=b,this.mc.N(!0)):(this.hd=null,this.mc.N(!1));this.rq()};z.m.iz=function(a){var b=z.ij;return{$:a.get(b.aa),Yy:a.get(b.Sc),prefix:a.get(b.jr),Ka:a.get(b.Qb),zc:a.get(b.xb),handle:a.get(b.gi)}};
z.m.vg=function(a,b){var c=this.iz(b),c=(0,z.bn)(c),c=(0,z.zf)(this.t.Qa.Ia,c),d=this.t.Fa(),f=this.t.Qa.n("SPAN","fyre-mention-space","\u00a0");this.hd?((0,z.Hf)(c,this.hd),$H(this)):d?d.bn(c):(d=new z.Ni(this.t.h()),d.mt().append(window.document.createTextNode(" ")),d.mt().append(c));(0,z.Ef)(f,c);aI(this,f);this.vo()};
z.m.Gx=function(){var a=this.t.Fa(),b=a.Cb();if(qH(new z.Ni(b),"fyre-mention"))return b;if(b.parentNode){if(qH(new z.Ni(b.parentNode),"fyre-mention"))return b.parentNode;if(0==a.Ja()&&b.previousSibling&&qH(new z.Ni(b.previousSibling),"fyre-mention"))return b.previousSibling}};
z.m.jy=function(a){if("@"===String.fromCharCode(a.charCode))return this.hd&&$H(this),this.hd=this.t.Qa.n("SPAN","fyre-mention-partial","@"),this.t.Fa().bn(this.hd),aI(this,this.hd.childNodes[0]),this.mc.N(!0),a.preventDefault(),!0};
z.m.hp=function(a){var b=13==a.keyCode,c=9==a.keyCode,d=8==a.keyCode,f=38==a.keyCode,g=40==a.keyCode;this.hd&&!this.hd.parentNode&&$H(this);if(d&&(d=this.Gx()))return(0,z.Gf)(d),!0;if(this.mc.ma()){if((0,z.ap)(this.R)&&(b||c))return this.vg("+mention",(0,z.ap)(this.R).k),a.preventDefault(),a.stopPropagation(),!0;if(f||g)f?(0,z.fp)(this.R):(0,z.ep)(this.R),a.preventDefault(),a.stopPropagation()}this.hd&&b&&$H(this)};
z.m.sk=function(a){var b=(0,z.hd)(this.AY,a.keyCode);(0,z.gn)(a)&&this.rq();b&&this.hd&&!bI(this)&&$H(this)};z.m.rq=function(){(0,z.op)(this.R,this.hd?(0,z.eg)(this.hd).substring(1):"")};z.m.cF=function(a){(0,z.x)((0,z.mf)("fyre-mention-space",a),z.If);(0,z.x)((0,z.mf)("fyre-mention-partial",a),z.If);(0,z.x)((0,z.mf)("fyre-mention",a),function(a){"@"==(0,z.eg)(a.childNodes[0])&&(0,z.Yf)(a.childNodes[0],"")});return a};z.m.AY=[9,32];z.m.vo=function(){this.R.Xd();this.mc.N(!1)};(0,z.u)(cI,z.Gr);cI.prototype.hb=function(a){cI.b.hb.call(this,a);this.qg=a.qg;this.xo=a.xo;this.B=a.B||new z.Ts;this.ga=this.B.get(this.B.g.Fn);this.rr={};this.Uc={};this.Qf=!1;this.parent=a.parent;this.Wm=a.Wm;this.view=a.view};cI.prototype.$R=function(a){if(a.shiftKey||a.ctrlKey||a.metaKey){var b=qH(new z.Ni(a.target),PI.Je),c=qH(new z.Ni(a.target.parentNode),PI.Je);if(b||c)return a.preventDefault(),a.stopPropagation(),!1}};
cI.prototype.ob={$q:"format",Hb:"media",Je:"mention",qd:"cancel",fc:"post",Av:"twitter",yv:"facebook",zv:"linkedin",dD:"google-plus",fi:"follow",Sn:"html"};var PI=cI.prototype.gg={dv:"fyre-editor-container",ev:"fyre-editor-editable",fv:"fyre-editor-field",VB:"fyre-editor-toolbar",Je:"fyre-mention",DD:"fyre-editor-small"};cI.prototype.M={qd:"cancel",xl:"fetchFriends",Il:"submitted",jD:"postTo",zC:"followChange",mZ:"contentChanged",On:"focus"};
cI.prototype.Ux=function(){var a=cI.prototype.ob,b=z.Jy.D(),c=z.Ky.D(),d=this.B.get(this.B.g.Kj);return[[a.$q,b,"","fyre-format-button"],[a.Je,b,"","fyre-mention-button"],[a.Hb,b,"","fyre-embed-button"],[a.fi,b,"","fyre-follow-button"],[a.fc,c,"","fyre-post-button fyre-post-button-enabled fyre-post-button-"+d],[a.qd,c,"Cancel","fyre-cancel-button"],[a.yv,c,"","fyre-post-to fyre-post-to-facebook"],[a.Av,c,"","fyre-post-to fyre-post-to-twitter"],[a.zv,c,"","fyre-post-to fyre-post-to-linkedin"],[a.dD,
c,"","fyre-post-to fyre-post-to-google-plus"]]};var QI=cI.prototype.ob,RI={};RI[QI.$q]=z.X.Hv;RI[QI.Hb]=z.X.Cn;RI[QI.Je]=z.X.SC;RI[QI.fi]=z.X.Zq;RI[QI.qd]=z.X.Yu;RI[QI.Av]=z.X.Dl;RI[QI.yv]=z.X.Bl;RI[QI.zv]=z.X.Cl;RI[QI.dD]=z.X.kD;z.m=cI.prototype;z.m.Zu=RI;z.m.Zv=function(a){return a==this.ob.fc||this.ga[this.Zu[a]]};
z.m.m=function(){this.B.on(this.B.kb(this.B.g.wf),this.op,this);this.B.on(this.B.kb(this.B.g.Ob),this.Zx,this);this.H.addListener("click",this.$R);(0,z.qh)(this.H,"shortcut_modifier_enter",(0,z.r)(this.kp,this));this.H.addListener("focus",this.wt(this.M.On));cI.b.m.call(this)};
z.m.Rb=function(){cI.b.Rb.call(this);var a="fyre-editor-"+(0,z.ka)(this.c);this.pa.$e('\x3cdiv class\x3d"fyre-editor-container"\x3e\x3cdiv class\x3d"fyre-editor-editable"\x3e\x3cdiv class\x3d"fyre-roundedpanel-content"\x3e\x3c/div\x3e\x3c/div\x3e'+(0,z.eo)()+'\x3cdiv class\x3d"fyre-editor-preview"\x3e\x3c/div\x3e\x3c/div\x3e').va();this.$j=(0,z.Ui)(this.pa,PI.dv);this.Vg=(0,z.Ui)(this.$j,PI.VB);this.Zb=(0,z.Ui)(this.$j,PI.ev);(0,z.Si)(this.Zb.os(),"id",a);(this.OK=this.ga[this.ga.e.Ml])?(this.H=new z.Ey(a),
this.ga[this.ga.e.fr]=null):this.H=new z.by(a);this.H.to=!1;z.I&&(this.H.et=!0);this.Rk();this.toolbar=this.dk(window.document);this.pa.va();this.pa.show();(0,z.By)(this.H);(0,z.N)(this.H.h(),PI.fv);this.ga[this.ga.e.fr]&&(this.H.addListener("keyup",this.dy,!1,this),this.H.addListener("keydown",this.cS,!1,this));this.xk=(0,z.ti)(this.Zb.element);this.Qy();this.ga[this.ga.e.mN]&&(jI(this),kI(this,!0));this.$s(z.w.P.pb+"/css/editor.css");a=this.ga[this.ga.e.In];(0,z.ja)(a)&&!(0,z.id)(a)?eI(this,a):
(0,z.id)(a)||(0,z.q)(a)&&(0,z.sa)(a,"http")?this.$s(a):(0,z.q)(a)&&dI(this,a)};z.m.$s=function(a){var b=this.H.Qa.sa();(0,z.q)(a)&&(a=[a]);(0,z.x)(a,function(a){(0,z.pb)(a,b)})};z.m.wu=function(a){this.OK?this.gu=!0:(this.gu=!a)?(0,z.si)(this.Zb.element,this.xk.height):this.dy()};z.m.cS=function(a){if(!this.gu){if(13==a.keyCode){var b=(0,z.bi)(this.Zb.element,"font-size").replace("px","");b||(b=12);fI(this,Math.floor(2.2*(0,window.parseInt)(b,10)))}27==a.keyCode&&iI(this)}};
z.m.dy=function(a){this.gu||a&&13==a.keyCode||fI(this)};z.m.Ce=function(a,b,c){this.H.Ce(a,b,c)};
z.m.j=function(){this.Zb=this.Vg=this.$j=null;if(this.H){this.p().$a(this.H,"shortcut_modifier_enter");var a=this.H;if(a.Hg==z.iy)throw Error("makeUneditable: Field is already uneditable");(0,z.xy)(a);(0,z.Nh)(a.aA);a.execCommand("clearlorem");var b=null;a.h()&&(b=(0,z.Ay)(a));(0,z.Dy)(a);var c=a.yc;z.PC==c.id&&(z.PC=null);a.Nr();if((0,z.q)(b)){(0,z.Xw)(c,b);b=a.yc;b.removeAttribute("contentEditable");b.removeAttribute("g_editable");b.removeAttribute("role");a.id?b.id=a.id:b.removeAttribute("id");
b.className=a.lX||"";var d=a.cssText;d?(0,z.pf)(b,{style:d}):b.removeAttribute("style");(0,z.q)(a.uz)&&((0,z.Zh)(b,"lineHeight",a.uz),a.uz=null)}a.hu();(0,z.oy)(a);z.I&&c.blur();a.execCommand("updatelorem");a.dispatchEvent("unload");this.H.q()}this.qb&&this.qb.q();this.bc&&this.bc.q();this.bc=null;cI.b.j.call(this)};z.m.Qy=function(){var a=this.B.get(this.B.g.Ob);a?this.Ce(!1,(0,z.va)(a),!0):z.F&&this.Ce(!0," ",!0)};
z.m.Rk=function(){(0,z.jy)(this.H,new z.Gx("P"));(0,z.jy)(this.H,new z.MA);(0,z.jy)(this.H,new z.Iw);(0,z.jy)(this.H,new z.Hv("shortcut_modifier_enter"))};z.m.dk=function(){var a;a=(0,z.ue)((0,z.Da)(this.Ux(),this.QP,this),wH);a.push(new z.Ny);a=(0,z.Wz)(a,this.Vg.element);(0,z.A)(this.Uc,this.FO,this);return a};z.m.QP=function(a){return this.KO.apply(this,a)};z.m.KO=function(a,b,c,d){if(this.Zv(a))return b=this.Xr(b,c,d),this.Uc[a]=b};z.m.Xr=function(a,b,c){a=new z.Ly(b,a);a.Hi(c,!0);return a};
z.m.um=(0,z.e)("toolbar");
z.m.FO=function(a,b){var c=this.ob;switch(b){case c.$q:(0,z.jy)(this.H,new z.GA);var c=(0,z.uf)("div","fyre-format-toolbar"),d=(0,z.Wz)("+bold +italic +underline +link +insertOrderedList +insertUnorderedList".split(" "),c);new z.HA(this.H,d);this.rr[this.ob.$q]=hI(this,a,c);break;case c.Hb:this.Qw(a);this.Rw();break;case c.Je:gI(this,a);(0,z.jy)(this.H,new ZH(this.B,this.Jh,this.rr[this.ob.Je]));(0,z.jy)(this.H,new YH);break;case c.qd:this.p().f(a,"action",this.wt(this.M.qd));break;case c.fi:this.p().f(a,
"action",this.CO,this);(0,z.Rg)(this.B,this.B.g.jv,this.fE,this);this.fE();break;case c.fc:this.BF(a);break;case c.yv:case c.Av:case c.zv:this.p().f(a,"action",this.wt(this.M.jD,b))}};z.m.Qw=function(a){this.p().f(a,"action",this.oy)};z.m.oy=function(){this.dispatchEvent({type:"mediaUploadClicked",wb:(0,z.r)(this.bc.co,this.bc)})};z.m.Rw=function(){var a=this.B.get(this.B.g.Hb);this.bc=new z.Nx(a);(0,z.Sm)(this.bc,this.Vg.element);this.bc.pc(this)};
z.m.fE=function(){var a=this.B.get(this.B.g.jv)?this.ga[this.ga.e.XD]:this.ga[this.ga.e.yC];this.Uc[this.ob.fi].lj(a)};z.m.CO=function(){var a=!this.B.get(this.B.g.jv);this.L(this.M.zC,a)};z.m.BF=function(a){var b=this.B.get(this.B.g.wf)?this.ga.e.ni:this.ga.e.mi;this.Wj(this.ga[b]);this.p().f(a,"action",this.kp,this)};z.m.Wj=function(a){this.Uc[this.ob.fc].lj(a)};z.m.VE=function(a){this.Uc[this.ob.qd].lj(a)};z.m.Xf=function(){this.Zb.append((0,z.Ti)(uH()))};
z.m.cs=function(){this.Qf=!0;var a=new z.Ni(this.Uc[cI.prototype.ob.fc].h());(0,z.Ze)(a.element,"fyre-post-button-enabled","fyre-post-button-disabled")};z.m.gx=function(){this.Qf=!1;var a=new z.Ni(this.Uc[cI.prototype.ob.fc].h());(0,z.Ze)(a.element,"fyre-post-button-disabled","fyre-post-button-enabled")};z.m.focus=function(){this.H.focus()};z.m.uh=function(a){this.focus();if(!z.F||(0,z.y)(9))if(!this.H.Fa()||a)a=this.H.field.childNodes,a.length&&(a=a[a.length-1].childNodes,(0,z.fx)(a[a.length-1]))};
z.m.nd=function(){var a=(0,z.Ui)(this.pa,"fyre-editor-spinner");a&&a.remove()};z.m.Yh=function(a){this.qb&&this.qb.q();this.qb=new z.Ev((0,z.ae)(this.ga,this.ga.ZB[a]||a,this.ga[this.ga.e.Fj]));this.qb.ta();this.Zb.append(this.qb.h());this.qb.show()};z.m.Gy=function(){this.qb&&this.qb.va()};z.m.op=function(){this.Wj(this.B.get(this.B.g.wf)?this.ga[this.ga.e.ni]:this.ga[this.ga.e.mi])};z.m.Zx=function(){var a=this.B.get(this.B.g.Ob);this.Ce(!1,(0,z.va)(a),!0)};
z.m.Gs=function(a){var b=this.Uc[cI.prototype.ob.Hb];b&&b.N(a)};z.m.clear=function(){var a=this.B.get(this.B.g.Hb);a&&a.reset();this.hh();this.B.set(this.B.g.Ob,"");iI(this);try{this.dy()}catch(b){}};z.m.dA=function(){var a=this.B.g,b={};b[a.Ob]=this.us();this.B.get(a.Hb)&&(b[a.Hb]=this.B.get(a.Hb).toJSON());return b};z.m.Kp=function(a){var b=this.B.g;this.B.set(b.Ob,a[b.Ob]);a[b.Hb]&&this.B.get(b.Hb).add(a[b.Hb])};z.m.Mp=function(a){this.H.execCommand("+mention",a)};
z.m.kp=function(){if(!this.Qf){var a=this.B.g,b=this.us(),c=this.ga.e,d=this.ga[c.PC];this.B.set(a.Ob,b);(0,z.eg)(this.H.field).length>=d?(this.ga[c.ig]=(0,z.ua)(this.ga[c.ig],d),this.Vh(c.ig)):(this.L(this.M.Il,{body:(0,z.Cg)(b),qg:this.qg,xo:this.xo,parent:this.parent,type:this.Wm}),(a=this.Uc[cI.prototype.ob.Hb])&&a.oc(!0))}};z.m.sq=function(){this.cs();this.Gy();this.Xf()};z.m.hh=function(){this.gx();this.nd()};z.m.Vh=function(a){this.hh();this.Yh(a)};z.m.us=function(){return(0,z.Ay)(this.H)};
z.m.Jr=function(){(0,z.Qi)(this.pa,PI.DD)};(0,z.u)(lI,z.Gr);var mI={qd:"fyre-cancel-button",$u:"fyre-editor-container",GL:"fyre-editor-editable",NL:"fyre-embed-button",fc:"fyre-post-button",Cv:"fyre-post-button-enabled",fD:"fyre-post-button-disabled",DD:"fyre-editor-small",$N:"fyre-editor-spinner",Rv:"fyre-editor-toolbar"},nI={Il:"submitted",qd:"cancel",On:"focus"};lI.prototype.hb=function(a){lI.b.hb.call(this,a);this.B=a.B||new z.Ts;this.ga=this.B.get(this.B.g.Fn);this.Uc={};this.Qf=!1;this.parent=a.parent;this.Wm=a.Wm};
var oI={qd:"cancel",Hb:"media",fc:"post"},SI={};SI.cancel=z.X.Yu;SI.media=z.X.Cn;z.m=lI.prototype;z.m.Zu=SI;z.m.Ux=function(){var a=this.ob,b=z.Ky.D(),c=z.Jy.D(),d=this.gg,f=this.B.get(this.B.g.Kj);return[[a.Hb,c,"",d.NL],[a.fc,b,"",(0,z.ua)("%s %s %s-%s",d.fc,d.Cv,d.fc,f)],[a.qd,b,"Cancel",d.qd]]};z.m.m=function(){this.B.on(this.B.kb(this.B.g.wf),this.op,this);this.B.on(this.B.kb(this.B.g.Ob),this.Zx,this);lI.b.m.call(this)};
z.m.Rb=function(){var a=this.gg,b="fyre-editor-"+(0,z.ka)(this.c);this.pa.$e('\x3cdiv class\x3d"fyre-editor-container"\x3e\x3cdiv class\x3d"fyre-editor-editable"\x3e\x3ctextarea class\x3d"fyre-editor-field-mobile fyre-roundedpanel-content"\x3e\x3c/textarea\x3e\x3c/div\x3e\x3cdiv class\x3d"fyre-editor-toolbar" role\x3d"toolbar"\x3e\x3c/div\x3e\x3c/div\x3e');this.$j=(0,z.Ui)(this.pa,a.$u);this.Vg=(0,z.Ui)(this.$j,a.Rv);this.Zb=(0,z.Ui)(this.$j,a.GL);this.UA=this.Zb.os();this.H=new z.by(b);this.dk();
this.xk=(0,z.ti)(this.Zb.element);this.Qy()};z.m.j=function(){this.Zb=this.Vg=this.$j=null;this.qb&&this.qb.q();this.bc&&this.bc.q();this.bc=null;lI.b.j.call(this)};z.m.fV=function(a,b){return a==b.get(b.g.aa)?b:null};z.m.Qy=function(){var a=this.B.get(this.B.g.Ob),b=this.B.g.wf?this.ga.e.ni:this.ga.e.mi;a&&qI(this,a);this.Wj(this.ga[b])};z.m.Zv=function(a){return a==this.ob.fc||this.ga[this.Zu[a]]};
z.m.dk=function(){var a;a=(0,z.ue)((0,z.Da)(this.Ux(),this.Xr,this),wH);a.push(new z.Ny);return(0,z.Wz)(a,this.Vg.element)};z.m.Xr=function(a){return this.AO.apply(this,a)};z.m.AO=function(a,b,c,d){if(this.Zv(a)){b=new z.Ly(c,b);b.Hi(d,!0);this.Uc[a]=b;switch(a){case this.ob.fc:this.p().f(b,"action",this.kp,this);break;case this.ob.qd:this.p().f(b,"action",this.wt(this.M.qd));break;case this.ob.Hb:this.Qw(b),this.Rw()}return b}};z.m.Qw=function(a){this.p().f(a,"action",this.oy)};
z.m.oy=function(){this.dispatchEvent({type:"mediaUploadClicked",wb:(0,z.r)(this.bc.co,this.bc)})};z.m.Rw=function(){var a=this.B.get(this.B.g.Hb);this.bc=new z.Nx(a);(0,z.Sm)(this.bc,this.Vg.element);this.bc.pc(this)};z.m.BF=function(a){this.Wj(this.ga[this.B.g.wf?this.ga.e.ni:this.ga.e.mi]);this.p().f(a,"action",this.kp,this)};z.m.Xf=function(){this.Zb.append((0,z.Ti)(uH()))};z.m.cs=function(){var a=this.gg,b=this.Uc[this.ob.fc].h();this.Qf=!0;(0,z.Ze)(b,a.Cv,a.fD)};
z.m.gx=function(){var a=this.gg,b=this.Uc[this.ob.fc].h();this.Qf=!1;(0,z.Ze)(b,a.fD,a.Cv)};z.m.focus=function(){this.UA.element.focus()};z.m.uh=function(){this.focus()};z.m.nd=function(){var a=(0,z.Ui)(this.pa,this.gg.$N);a&&a.remove()};z.m.Yh=function(a){this.qb&&this.qb.q();this.qb=new z.Ev((0,z.ae)(this.ga,this.ga.ZB[a]||a,this.ga[this.ga.e.Fj]));this.qb.ta();this.Zb.append(this.qb.h());this.qb.show()};z.m.Gy=function(){this.qb&&this.qb.va()};z.m.Wj=function(a){this.Uc[this.ob.fc].lj(a)};
z.m.VE=function(a){this.Uc[this.ob.qd].lj(a)};z.m.op=function(){this.Wj(this.B.get(this.B.g.wf)?this.ga[this.ga.e.ni]:this.ga[this.ga.e.mi])};z.m.Zx=function(){var a=this.B.get(this.B.g.Ob);qI(this,a)};z.m.clear=function(){var a=this.B.get(this.B.g.Hb);qI(this,"");this.B.set(this.B.g.Ob,"");this.hh();a&&a.reset()};z.m.dA=function(){var a={};a[this.B.g.Ob]=pI(this);return a};z.m.Kp=function(a){var b=this.B.g;this.B.set(b.Ob,a[b.Ob])};z.m.Mp=(0,z.ba)();
z.m.kp=function(){if(!this.Qf){var a=this.B.g,b=pI(this);this.B.set(a.Ob,b);this.L(this.M.Il,{body:b,qg:this.qg,xo:this.xo,parent:this.parent,type:this.Wm})}};z.m.sq=function(){this.bc&&this.bc.va();this.cs();this.Gy();this.Xf()};z.m.hh=function(){this.gx();this.nd()};z.m.Vh=function(a){this.hh();this.Yh(a)};z.m.wu=function(){(0,z.si)(this.Zb.element,100)};z.m.us=(0,z.l)("");z.m.Gs=function(a){var b=this.Uc[cI.prototype.ob.Hb];b&&b.N(a)};z.m.Jr=function(){(0,z.Qi)(this.pa,"fyre-editor-small")};(0,z.u)(rI,z.oo);(0,z.Ie)(rI);z.m=rI.prototype;z.m.ne=(0,z.ba)();z.m.Q=function(a,b){(0,z.xo)(a,!1);a.zf&=-256;(0,z.Bo)(a,32,!1);rI.b.Q.call(this,a,b);a.Ca(b.value);return b};z.m.n=function(a){(0,z.xo)(a,!1);a.zf&=-256;(0,z.Bo)(a,32,!1);return a.X().n("textarea",{"class":this.Mi(a).join(" "),disabled:!a.isEnabled()},a.Pc()||"")};z.m.Ld=function(a){return"TEXTAREA"==a.tagName};z.m.Xh=z.p;z.m.Fg=function(a){return a.isEnabled()};z.m.Be=z.p;
z.m.ed=function(a,b,c){rI.b.ed.call(this,a,b,c);(a=a.h())&&1==b&&(a.disabled=c)};z.m.Ge=z.p;z.m.Ca=function(a,b){a&&(a.value=b)};z.m.T=(0,z.l)("goog-textarea");(0,z.u)(sI,z.vo);var TI=z.H||z.I;z.m=sI.prototype;z.m.Jm=!1;z.m.Ui=0;z.m.hV=0;z.m.Ek=0;z.m.NH=!1;z.m.Bt=!1;z.m.Yz=!1;z.m.Xz=!1;z.m.kA=function(a){this.Ek=a;this.resize()};z.m.Nb=function(a){this.Ca(String(a))};z.m.ea=function(){return this.h().value};z.m.Ca=function(a){sI.b.Ca.call(this,a);this.resize()};z.m.oc=function(a){sI.b.oc.call(this,a);this.h().disabled=!a};z.m.resize=function(){this.h()&&this.Bs()};
z.m.m=function(){sI.b.m.call(this);var a=this.h();(0,z.Zh)(a,{overflowY:"hidden",overflowX:"auto",boxSizing:"border-box",MsBoxSizing:"border-box",WebkitBoxSizing:"border-box",MozBoxSizing:"border-box"});this.Tp=(0,z.Di)(a);this.NE=(0,z.oi)(a);this.p().f(a,"scroll",this.Bs).f(a,"focus",this.Bs).f(a,"keyup",this.Bs).f(a,"mouseup",this.vV);this.resize()};
z.m.Bs=function(){if(!this.Jm){var a=!1;this.Jm=!0;var b=this.h(),c=this.Ui;if(b.scrollHeight){var d=!1,f=!1,g=wI(this),h=b.offsetHeight,k=uI(this),n=vI(this);k&&g<k?(xI(this,k),d=!0):n&&g>n?(xI(this,n),b.style.overflowY="",f=!0):h!=g?xI(this,g):this.Ui||(this.Ui=g);d||f||!TI||(a=!0)}else yI(this);this.Jm=!1;a&&(a=this.h(),this.Jm||(this.Jm=!0,(d=a.scrollHeight)?(f=wI(this),b=uI(this),g=vI(this),b&&f<=b||g&&f>=g||(g=this.Tp,a.style.paddingBottom=g.bottom+1+"px",wI(this)==f&&(a.style.paddingBottom=
g.bottom+d+"px",a.scrollTop=0,d=wI(this)-d,d>=b?xI(this,d):xI(this,b)),a.style.paddingBottom=g.bottom+"px")):yI(this),this.Jm=!1));c!=this.Ui&&this.dispatchEvent("resize")}};z.m.vV=function(){var a=this.h(),b=a.offsetHeight;a.filters&&a.filters.length&&(a=a.filters.item("DXImageTransform.Microsoft.DropShadow"))&&(b-=a.offX);b!=this.Ui&&(this.Ui=this.Ek=b)};(0,z.u)(z.vt,z.Gr);z.m=z.vt.prototype;z.m.gg={gc:"fyre-editor-rawhtml",HL:"fyre-editor-preview"};
z.m.hb=function(a){z.vt.b.hb.call(this,a);this.Oh=a.Oh;this.sE=a.xt;this.B=a.B;this.s=new z.Jj;this.Bu=a.UX||"fyre-editorstate-main";this.Wl=new yH(a,this);zI(this,this.B);z.Yb?(this.G=new lI({B:this.B}),this.Fh=!0):(this.G=new cI({B:this.B}),this.G.on(this.G.M.jD,this.nT,this),this.G.on(this.G.M.zC,this.sS,this),this.G.on(this.G.M.xl,(0,z.r)(this.ju,this,!0),this),this.Vs=new zH(this.s),this.p().f(this.Vs,"canceled",this.pT),this.Yt=this.G.Xr(z.Jy.D(),"","fyre-html-button"),this.p().f(this.Yt,"action",
this.sT));this.K(this.G);z.Q.on(z.Q.kb(z.Q.g.Pv),function(a){a&&(this.G.cs(),this.G.Yh(z.X.Kn))},this);this.Kp();this.Rj=!1;this.HE=[];this.oB=!1;this.G.on(this.G.M.Il,this.tJ,this)};z.m.Rb=function(){z.vt.b.Rb.call(this);this.G.Q(this.c,!0);AI(this);var a=this.sE||z.Q.Bd();this.G.Gs(a)};z.m.m=function(){this.p().zk(this.c,"click",this.Yc);z.vt.b.m.call(this)};z.m.yg=function(){this.B.set(this.B.g.wf,z.Q.id);var a=this.sE||z.Q.Bd();this.G.ca&&this.G.Gs(a)};
z.m.sS=function(a){(0,z.Zl)(this.C.zb,this.C.u.w(),(0,z.r)(this.C.u.qs,this.C.u,a))};
z.m.nT=function(a,b){var c=null;switch(a){case "twitter":c=1;break;case "facebook":c=2;break;case "linkedin":c=4;break;case "google-plus":c=3}var d=new z.Ni(b.target.Aa()),f=this.G.B.g,g=this.G.B.get(f.nb),h=this.C.zb;(0,z.Zl)(this.C.zb,this.C.u.w(),(0,z.r)(h.Xo,h,z.Q,c,(0,z.r)(function(){(0,z.hd)(g,a)?((0,z.qe)(g,a),this.G.B.set(f.nb,g),(0,z.Ri)(d,"fyre-post-to-selected")):(g.push(a),this.G.B.set(f.nb,g),(0,z.Qi)(d,"fyre-post-to-selected"))},this),(0,z.r)(function(){(0,z.Ri)(d,"fyre-post-to-selected")},
this)),z.p)};z.m.zw=function(){var a=this.s,b=this.B;a.set(z.Xj,(0,z.Cg)(b.get(b.g.Ob)));a.set(z.Rj,this.C.u.w());a.set(z.Wj,this.Oh);var c=b.get(b.g.Hb),d=a.get(z.ik);d.reset();c.forEach((0,z.r)(d.add,d));var f=0,g={twitter:a.nb.Ib,facebook:a.nb.Pb,linkedin:a.nb.ah};(0,z.x)(b.get(b.g.nb),function(a){f|=g[a]});a.set(a.g.nb,f);return a};z.m.Kp=function(){var a;a=z.Br.get(this.Bu,void 0);if(a=void 0===a?a:(0,z.pg)((0,z.ke)(a)))this.G.Kp(a),z.Br.remove(this.Bu)};
z.m.Yc=function(){this.oB||z.$i.subscribe("user_logged_in",this.ju,this);this.oB=!0;this.ju()};z.m.ju=function(a){(z.Q.id&&this.oB||a)&&(0,z.$l)(this.C.zb,a,(0,z.r)(this.AT,this))};z.m.AT=function(){this.G.Jh.L(JI.lC)};z.m.sq=function(){this.G.sq()};z.m.hh=function(){this.G.hh()};z.m.clear=function(){this.s.set(this.s.g.gc,null);this.s.get(this.s.g.Dj).reset();this.G.clear()};z.m.Vh=function(a){this.G.Vh(a)};z.m.Uk=function(a,b){this.Rj=a;b&&(this.HE=(0,z.id)(b)?b:[b])};z.m.wu=function(a){this.G.wu(a)};
z.m.show=function(){(new z.Ni(this.c)).show();var a=(0,z.jf)(this.c);if(this.Rj)if(this.p().f(a,"click",this.ZG,!0),z.F){var b;try{b=a.activeElement}catch(c){}for(;b&&"IFRAME"==b.nodeName;){try{var d=(0,z.Xf)(b)}catch(f){break}a=d;b=a.activeElement}this.p().f(a,"click",this.ZG,!0);this.p().f(a,"deactivate",this.XG)}else this.p().f(a,"blur",this.XG)};z.m.va=function(){(new z.Ni(this.c)).va()};z.m.cf=function(){return(new z.Ni(this.c)).cf()};
z.m.ZG=function(a){var b=a.target;this.Rj&&(a=(0,z.Ea)(this.HE,function(a){return(0,z.Sf)(a,b)}),(0,z.Sf)(this.c,b)||a||this.cf()||(z.F?window.setTimeout((0,z.r)(this.va,this),250):this.va()))};z.m.XG=function(a){var b=(0,z.jf)(this.c);if(z.F||z.C||z.H){if(a=b.activeElement,!a||(0,z.Sf)(this.c,a)||"BODY"==a.tagName)return}else if(a.target!=b)return;this.cf()||(z.F?window.setTimeout((0,z.r)(this.va,this),250):this.va())};
z.m.j=function(){z.Q.off(null,null,this);this.p().q();this.Wl&&this.Wl.q();this.G.off&&this.G.off();this.G.q();z.vt.b.j.call(this)};z.m.sT=function(){var a=new sI,b=this.s.get(this.s.g.gc);a.xr(this.gg.gc);b&&a.Nb(b.body);b=z.Rn.D();(0,z.En)(b,z.W.get(z.W.e.wL));b.K(a,!0);var c=(0,z.r)(function(){var b=a.ea(),b=(0,z.Jd)(null==b?"":String(b))?null:{body:b};this.s.set(this.s.g.gc,b)},this);(0,z.Tn)(b,c);var d=this.Rj;this.Uk(!1);c=(0,z.r)(function(){this.Uk(d)},this);this.p().f(b,z.AB,c);b.open();a.kA(200)};
z.m.pT=function(){this.s.set(this.s.g.gc,null)};z.m.tJ=function(){this.sq()};(0,z.u)(BI,z.T);BI.prototype.F=function(a){a.innerHTML='\x3cdiv class\x3d"fyre-editor-disabled"\x3e\x3cspan class\x3d"fyre-editor-locked"\x3e\x3c/span\x3e This conversation is currently closed to new comments.\x3c/div\x3e';this.c=a};BI.prototype.um=z.p;BI.prototype.Gs=z.p;(0,z.u)(z.ov,z.vt);z.m=z.ov.prototype;z.m.F=function(a){z.ov.b.F.call(this,a);this.ca=!0;this.hB();this.J.Dh()&&this.G.H&&(this.G.H.to=!0)};z.m.bu=function(a){this.J=a;this.hB();(0,z.Rg)(z.Q,z.Qk.rc,this.hB,this)};z.m.hB=function(){this.ca&&this.J&&(!z.Q.get(z.Qk.rc)&&this.J.se()?this.va():this.show())};
z.m.hb=function(a){this.PH=!1;a.hF&&this.bu(a.hF);var b=new z.Ts;b.set(b.g.Mj,z.Q);var c=(0,z.jt)(a);this.J.se();var d=this.J.Dh(),f=!this.J.get(z.U.rf);d&&(c[c.e.mi]=z.W.get(z.W.e.LC),c[c.e.ni]=z.W.get(z.W.e.LC),z.Yb||(d=z.W.get(z.W.e.WM),z.jc||(d=z.W.get(z.W.e.UM)),b.set(b.g.Ob,d)));f?this.G=new BI:(b.set(b.g.Fn,c),a.B=b,z.ov.b.hb.call(this,a),this.G.on(this.G.M.On,this.wh,this))};
z.m.tJ=function(){var a=this.zw();this.C.u.w();var b=(0,z.Jd)(a.get(a.g.Dc));if(b=(b=b&&!a.get(a.g.Dj).length)&&!a.get(a.g.gc))this.G.Vh(z.X.Gj);else{this.G.sq();(0,z.Yq)(this.C.bw,a);try{(0,z.Zl)(this.C.zb,this.C.u.w(),(0,z.r)(this.C.ya.postMessage,this.C.ya,a,(0,z.r)(this.Wl.GP,this.Wl),(0,z.r)(this.Wl.FP,this.Wl)),(0,z.r)(this.G.hh,this.G))}catch(c){if(!(c instanceof z.yr))return;this.G.Vh(z.X.ig)}this.dispatchEvent({type:"postComment"})}};
z.m.wh=function(){this.J.Dh()&&!this.PH&&this.G.H.to&&this.G.Ce(!0,null,!0);this.G.H.to=!1;this.PH=!0};z.m.yg=function(){z.ov.b.yg.call(this);if(this.ca){var a=this.C.u.w(),b=z.Q.get(z.Qk.rc);a.se()&&!b?this.va():this.show();AI(this)}};})(fyre.conv);
